// Code generated by ent, DO NOT EDIT.

package usersonaccessgroups

import (
	"shared/infrastructure/persistence/postgres/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldEQ(FieldUserID, v))
}

// AccessGroupID applies equality check predicate on the "access_group_id" field. It's identical to AccessGroupIDEQ.
func AccessGroupID(v int) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldEQ(FieldAccessGroupID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldNotIn(FieldUserID, vs...))
}

// AccessGroupIDEQ applies the EQ predicate on the "access_group_id" field.
func AccessGroupIDEQ(v int) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldEQ(FieldAccessGroupID, v))
}

// AccessGroupIDNEQ applies the NEQ predicate on the "access_group_id" field.
func AccessGroupIDNEQ(v int) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldNEQ(FieldAccessGroupID, v))
}

// AccessGroupIDIn applies the In predicate on the "access_group_id" field.
func AccessGroupIDIn(vs ...int) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldIn(FieldAccessGroupID, vs...))
}

// AccessGroupIDNotIn applies the NotIn predicate on the "access_group_id" field.
func AccessGroupIDNotIn(vs ...int) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldNotIn(FieldAccessGroupID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccessGroup applies the HasEdge predicate on the "access_group" edge.
func HasAccessGroup() predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccessGroupTable, AccessGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccessGroupWith applies the HasEdge predicate on the "access_group" edge with a given conditions (other predicates).
func HasAccessGroupWith(preds ...predicate.AccessGroup) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(func(s *sql.Selector) {
		step := newAccessGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsersOnAccessGroups) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsersOnAccessGroups) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsersOnAccessGroups) predicate.UsersOnAccessGroups {
	return predicate.UsersOnAccessGroups(sql.NotPredicates(p))
}
