// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"shared/infrastructure/persistence/postgres/ent/accessgroup"
	"shared/infrastructure/persistence/postgres/ent/predicate"
	"shared/infrastructure/persistence/postgres/ent/usersonaccessgroups"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessGroupQuery is the builder for querying AccessGroup entities.
type AccessGroupQuery struct {
	config
	ctx        *QueryContext
	order      []accessgroup.OrderOption
	inters     []Interceptor
	predicates []predicate.AccessGroup
	withUsers  *UsersOnAccessGroupsQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AccessGroupQuery builder.
func (agq *AccessGroupQuery) Where(ps ...predicate.AccessGroup) *AccessGroupQuery {
	agq.predicates = append(agq.predicates, ps...)
	return agq
}

// Limit the number of records to be returned by this query.
func (agq *AccessGroupQuery) Limit(limit int) *AccessGroupQuery {
	agq.ctx.Limit = &limit
	return agq
}

// Offset to start from.
func (agq *AccessGroupQuery) Offset(offset int) *AccessGroupQuery {
	agq.ctx.Offset = &offset
	return agq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (agq *AccessGroupQuery) Unique(unique bool) *AccessGroupQuery {
	agq.ctx.Unique = &unique
	return agq
}

// Order specifies how the records should be ordered.
func (agq *AccessGroupQuery) Order(o ...accessgroup.OrderOption) *AccessGroupQuery {
	agq.order = append(agq.order, o...)
	return agq
}

// QueryUsers chains the current query on the "users" edge.
func (agq *AccessGroupQuery) QueryUsers() *UsersOnAccessGroupsQuery {
	query := (&UsersOnAccessGroupsClient{config: agq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := agq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := agq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accessgroup.Table, accessgroup.FieldID, selector),
			sqlgraph.To(usersonaccessgroups.Table, usersonaccessgroups.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, accessgroup.UsersTable, accessgroup.UsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(agq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AccessGroup entity from the query.
// Returns a *NotFoundError when no AccessGroup was found.
func (agq *AccessGroupQuery) First(ctx context.Context) (*AccessGroup, error) {
	nodes, err := agq.Limit(1).All(setContextOp(ctx, agq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{accessgroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (agq *AccessGroupQuery) FirstX(ctx context.Context) *AccessGroup {
	node, err := agq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AccessGroup ID from the query.
// Returns a *NotFoundError when no AccessGroup ID was found.
func (agq *AccessGroupQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = agq.Limit(1).IDs(setContextOp(ctx, agq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{accessgroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (agq *AccessGroupQuery) FirstIDX(ctx context.Context) int {
	id, err := agq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AccessGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AccessGroup entity is found.
// Returns a *NotFoundError when no AccessGroup entities are found.
func (agq *AccessGroupQuery) Only(ctx context.Context) (*AccessGroup, error) {
	nodes, err := agq.Limit(2).All(setContextOp(ctx, agq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{accessgroup.Label}
	default:
		return nil, &NotSingularError{accessgroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (agq *AccessGroupQuery) OnlyX(ctx context.Context) *AccessGroup {
	node, err := agq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AccessGroup ID in the query.
// Returns a *NotSingularError when more than one AccessGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (agq *AccessGroupQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = agq.Limit(2).IDs(setContextOp(ctx, agq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{accessgroup.Label}
	default:
		err = &NotSingularError{accessgroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (agq *AccessGroupQuery) OnlyIDX(ctx context.Context) int {
	id, err := agq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AccessGroups.
func (agq *AccessGroupQuery) All(ctx context.Context) ([]*AccessGroup, error) {
	ctx = setContextOp(ctx, agq.ctx, "All")
	if err := agq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AccessGroup, *AccessGroupQuery]()
	return withInterceptors[[]*AccessGroup](ctx, agq, qr, agq.inters)
}

// AllX is like All, but panics if an error occurs.
func (agq *AccessGroupQuery) AllX(ctx context.Context) []*AccessGroup {
	nodes, err := agq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AccessGroup IDs.
func (agq *AccessGroupQuery) IDs(ctx context.Context) (ids []int, err error) {
	if agq.ctx.Unique == nil && agq.path != nil {
		agq.Unique(true)
	}
	ctx = setContextOp(ctx, agq.ctx, "IDs")
	if err = agq.Select(accessgroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (agq *AccessGroupQuery) IDsX(ctx context.Context) []int {
	ids, err := agq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (agq *AccessGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, agq.ctx, "Count")
	if err := agq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, agq, querierCount[*AccessGroupQuery](), agq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (agq *AccessGroupQuery) CountX(ctx context.Context) int {
	count, err := agq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (agq *AccessGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, agq.ctx, "Exist")
	switch _, err := agq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (agq *AccessGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := agq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AccessGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (agq *AccessGroupQuery) Clone() *AccessGroupQuery {
	if agq == nil {
		return nil
	}
	return &AccessGroupQuery{
		config:     agq.config,
		ctx:        agq.ctx.Clone(),
		order:      append([]accessgroup.OrderOption{}, agq.order...),
		inters:     append([]Interceptor{}, agq.inters...),
		predicates: append([]predicate.AccessGroup{}, agq.predicates...),
		withUsers:  agq.withUsers.Clone(),
		// clone intermediate query.
		sql:  agq.sql.Clone(),
		path: agq.path,
	}
}

// WithUsers tells the query-builder to eager-load the nodes that are connected to
// the "users" edge. The optional arguments are used to configure the query builder of the edge.
func (agq *AccessGroupQuery) WithUsers(opts ...func(*UsersOnAccessGroupsQuery)) *AccessGroupQuery {
	query := (&UsersOnAccessGroupsClient{config: agq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	agq.withUsers = query
	return agq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AccessGroup.Query().
//		GroupBy(accessgroup.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (agq *AccessGroupQuery) GroupBy(field string, fields ...string) *AccessGroupGroupBy {
	agq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AccessGroupGroupBy{build: agq}
	grbuild.flds = &agq.ctx.Fields
	grbuild.label = accessgroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.AccessGroup.Query().
//		Select(accessgroup.FieldName).
//		Scan(ctx, &v)
func (agq *AccessGroupQuery) Select(fields ...string) *AccessGroupSelect {
	agq.ctx.Fields = append(agq.ctx.Fields, fields...)
	sbuild := &AccessGroupSelect{AccessGroupQuery: agq}
	sbuild.label = accessgroup.Label
	sbuild.flds, sbuild.scan = &agq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AccessGroupSelect configured with the given aggregations.
func (agq *AccessGroupQuery) Aggregate(fns ...AggregateFunc) *AccessGroupSelect {
	return agq.Select().Aggregate(fns...)
}

func (agq *AccessGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range agq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, agq); err != nil {
				return err
			}
		}
	}
	for _, f := range agq.ctx.Fields {
		if !accessgroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if agq.path != nil {
		prev, err := agq.path(ctx)
		if err != nil {
			return err
		}
		agq.sql = prev
	}
	return nil
}

func (agq *AccessGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AccessGroup, error) {
	var (
		nodes       = []*AccessGroup{}
		_spec       = agq.querySpec()
		loadedTypes = [1]bool{
			agq.withUsers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AccessGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AccessGroup{config: agq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, agq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := agq.withUsers; query != nil {
		if err := agq.loadUsers(ctx, query, nodes,
			func(n *AccessGroup) { n.Edges.Users = []*UsersOnAccessGroups{} },
			func(n *AccessGroup, e *UsersOnAccessGroups) { n.Edges.Users = append(n.Edges.Users, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (agq *AccessGroupQuery) loadUsers(ctx context.Context, query *UsersOnAccessGroupsQuery, nodes []*AccessGroup, init func(*AccessGroup), assign func(*AccessGroup, *UsersOnAccessGroups)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*AccessGroup)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(usersonaccessgroups.FieldAccessGroupID)
	}
	query.Where(predicate.UsersOnAccessGroups(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(accessgroup.UsersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AccessGroupID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "access_group_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (agq *AccessGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := agq.querySpec()
	_spec.Node.Columns = agq.ctx.Fields
	if len(agq.ctx.Fields) > 0 {
		_spec.Unique = agq.ctx.Unique != nil && *agq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, agq.driver, _spec)
}

func (agq *AccessGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(accessgroup.Table, accessgroup.Columns, sqlgraph.NewFieldSpec(accessgroup.FieldID, field.TypeInt))
	_spec.From = agq.sql
	if unique := agq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if agq.path != nil {
		_spec.Unique = true
	}
	if fields := agq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accessgroup.FieldID)
		for i := range fields {
			if fields[i] != accessgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := agq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := agq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := agq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := agq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (agq *AccessGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(agq.driver.Dialect())
	t1 := builder.Table(accessgroup.Table)
	columns := agq.ctx.Fields
	if len(columns) == 0 {
		columns = accessgroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if agq.sql != nil {
		selector = agq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if agq.ctx.Unique != nil && *agq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range agq.predicates {
		p(selector)
	}
	for _, p := range agq.order {
		p(selector)
	}
	if offset := agq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := agq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AccessGroupGroupBy is the group-by builder for AccessGroup entities.
type AccessGroupGroupBy struct {
	selector
	build *AccessGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aggb *AccessGroupGroupBy) Aggregate(fns ...AggregateFunc) *AccessGroupGroupBy {
	aggb.fns = append(aggb.fns, fns...)
	return aggb
}

// Scan applies the selector query and scans the result into the given value.
func (aggb *AccessGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aggb.build.ctx, "GroupBy")
	if err := aggb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AccessGroupQuery, *AccessGroupGroupBy](ctx, aggb.build, aggb, aggb.build.inters, v)
}

func (aggb *AccessGroupGroupBy) sqlScan(ctx context.Context, root *AccessGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(aggb.fns))
	for _, fn := range aggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*aggb.flds)+len(aggb.fns))
		for _, f := range *aggb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*aggb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aggb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AccessGroupSelect is the builder for selecting fields of AccessGroup entities.
type AccessGroupSelect struct {
	*AccessGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ags *AccessGroupSelect) Aggregate(fns ...AggregateFunc) *AccessGroupSelect {
	ags.fns = append(ags.fns, fns...)
	return ags
}

// Scan applies the selector query and scans the result into the given value.
func (ags *AccessGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ags.ctx, "Select")
	if err := ags.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AccessGroupQuery, *AccessGroupSelect](ctx, ags.AccessGroupQuery, ags, ags.inters, v)
}

func (ags *AccessGroupSelect) sqlScan(ctx context.Context, root *AccessGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ags.fns))
	for _, fn := range ags.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ags.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ags.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
