// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"shared/infrastructure/persistence/postgres/ent/accessgroup"
	"shared/infrastructure/persistence/postgres/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessGroupDelete is the builder for deleting a AccessGroup entity.
type AccessGroupDelete struct {
	config
	hooks    []Hook
	mutation *AccessGroupMutation
}

// Where appends a list predicates to the AccessGroupDelete builder.
func (agd *AccessGroupDelete) Where(ps ...predicate.AccessGroup) *AccessGroupDelete {
	agd.mutation.Where(ps...)
	return agd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (agd *AccessGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, agd.sqlExec, agd.mutation, agd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (agd *AccessGroupDelete) ExecX(ctx context.Context) int {
	n, err := agd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (agd *AccessGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accessgroup.Table, sqlgraph.NewFieldSpec(accessgroup.FieldID, field.TypeInt))
	if ps := agd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, agd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	agd.mutation.done = true
	return affected, err
}

// AccessGroupDeleteOne is the builder for deleting a single AccessGroup entity.
type AccessGroupDeleteOne struct {
	agd *AccessGroupDelete
}

// Where appends a list predicates to the AccessGroupDelete builder.
func (agdo *AccessGroupDeleteOne) Where(ps ...predicate.AccessGroup) *AccessGroupDeleteOne {
	agdo.agd.mutation.Where(ps...)
	return agdo
}

// Exec executes the deletion query.
func (agdo *AccessGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := agdo.agd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accessgroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (agdo *AccessGroupDeleteOne) ExecX(ctx context.Context) {
	if err := agdo.Exec(ctx); err != nil {
		panic(err)
	}
}
