// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shared/infrastructure/persistence/postgres/ent/accessgroup"
	"shared/infrastructure/persistence/postgres/ent/usersonaccessgroups"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessGroupCreate is the builder for creating a AccessGroup entity.
type AccessGroupCreate struct {
	config
	mutation *AccessGroupMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (agc *AccessGroupCreate) SetName(s string) *AccessGroupCreate {
	agc.mutation.SetName(s)
	return agc
}

// SetCreatedAt sets the "created_at" field.
func (agc *AccessGroupCreate) SetCreatedAt(t time.Time) *AccessGroupCreate {
	agc.mutation.SetCreatedAt(t)
	return agc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (agc *AccessGroupCreate) SetNillableCreatedAt(t *time.Time) *AccessGroupCreate {
	if t != nil {
		agc.SetCreatedAt(*t)
	}
	return agc
}

// SetUpdatedAt sets the "updated_at" field.
func (agc *AccessGroupCreate) SetUpdatedAt(t time.Time) *AccessGroupCreate {
	agc.mutation.SetUpdatedAt(t)
	return agc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (agc *AccessGroupCreate) SetNillableUpdatedAt(t *time.Time) *AccessGroupCreate {
	if t != nil {
		agc.SetUpdatedAt(*t)
	}
	return agc
}

// SetDeactivatedAt sets the "deactivated_at" field.
func (agc *AccessGroupCreate) SetDeactivatedAt(t time.Time) *AccessGroupCreate {
	agc.mutation.SetDeactivatedAt(t)
	return agc
}

// SetNillableDeactivatedAt sets the "deactivated_at" field if the given value is not nil.
func (agc *AccessGroupCreate) SetNillableDeactivatedAt(t *time.Time) *AccessGroupCreate {
	if t != nil {
		agc.SetDeactivatedAt(*t)
	}
	return agc
}

// SetID sets the "id" field.
func (agc *AccessGroupCreate) SetID(i int) *AccessGroupCreate {
	agc.mutation.SetID(i)
	return agc
}

// AddUserIDs adds the "users" edge to the UsersOnAccessGroups entity by IDs.
func (agc *AccessGroupCreate) AddUserIDs(ids ...int) *AccessGroupCreate {
	agc.mutation.AddUserIDs(ids...)
	return agc
}

// AddUsers adds the "users" edges to the UsersOnAccessGroups entity.
func (agc *AccessGroupCreate) AddUsers(u ...*UsersOnAccessGroups) *AccessGroupCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return agc.AddUserIDs(ids...)
}

// Mutation returns the AccessGroupMutation object of the builder.
func (agc *AccessGroupCreate) Mutation() *AccessGroupMutation {
	return agc.mutation
}

// Save creates the AccessGroup in the database.
func (agc *AccessGroupCreate) Save(ctx context.Context) (*AccessGroup, error) {
	agc.defaults()
	return withHooks(ctx, agc.sqlSave, agc.mutation, agc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (agc *AccessGroupCreate) SaveX(ctx context.Context) *AccessGroup {
	v, err := agc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (agc *AccessGroupCreate) Exec(ctx context.Context) error {
	_, err := agc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (agc *AccessGroupCreate) ExecX(ctx context.Context) {
	if err := agc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (agc *AccessGroupCreate) defaults() {
	if _, ok := agc.mutation.CreatedAt(); !ok {
		v := accessgroup.DefaultCreatedAt()
		agc.mutation.SetCreatedAt(v)
	}
	if _, ok := agc.mutation.UpdatedAt(); !ok {
		v := accessgroup.DefaultUpdatedAt()
		agc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (agc *AccessGroupCreate) check() error {
	if _, ok := agc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AccessGroup.name"`)}
	}
	if v, ok := agc.mutation.Name(); ok {
		if err := accessgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccessGroup.name": %w`, err)}
		}
	}
	if _, ok := agc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccessGroup.created_at"`)}
	}
	if _, ok := agc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccessGroup.updated_at"`)}
	}
	if v, ok := agc.mutation.ID(); ok {
		if err := accessgroup.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AccessGroup.id": %w`, err)}
		}
	}
	return nil
}

func (agc *AccessGroupCreate) sqlSave(ctx context.Context) (*AccessGroup, error) {
	if err := agc.check(); err != nil {
		return nil, err
	}
	_node, _spec := agc.createSpec()
	if err := sqlgraph.CreateNode(ctx, agc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	agc.mutation.id = &_node.ID
	agc.mutation.done = true
	return _node, nil
}

func (agc *AccessGroupCreate) createSpec() (*AccessGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &AccessGroup{config: agc.config}
		_spec = sqlgraph.NewCreateSpec(accessgroup.Table, sqlgraph.NewFieldSpec(accessgroup.FieldID, field.TypeInt))
	)
	if id, ok := agc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := agc.mutation.Name(); ok {
		_spec.SetField(accessgroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := agc.mutation.CreatedAt(); ok {
		_spec.SetField(accessgroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := agc.mutation.UpdatedAt(); ok {
		_spec.SetField(accessgroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := agc.mutation.DeactivatedAt(); ok {
		_spec.SetField(accessgroup.FieldDeactivatedAt, field.TypeTime, value)
		_node.DeactivatedAt = value
	}
	if nodes := agc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accessgroup.UsersTable,
			Columns: []string{accessgroup.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AccessGroupCreateBulk is the builder for creating many AccessGroup entities in bulk.
type AccessGroupCreateBulk struct {
	config
	err      error
	builders []*AccessGroupCreate
}

// Save creates the AccessGroup entities in the database.
func (agcb *AccessGroupCreateBulk) Save(ctx context.Context) ([]*AccessGroup, error) {
	if agcb.err != nil {
		return nil, agcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(agcb.builders))
	nodes := make([]*AccessGroup, len(agcb.builders))
	mutators := make([]Mutator, len(agcb.builders))
	for i := range agcb.builders {
		func(i int, root context.Context) {
			builder := agcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccessGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, agcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, agcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, agcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (agcb *AccessGroupCreateBulk) SaveX(ctx context.Context) []*AccessGroup {
	v, err := agcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (agcb *AccessGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := agcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (agcb *AccessGroupCreateBulk) ExecX(ctx context.Context) {
	if err := agcb.Exec(ctx); err != nil {
		panic(err)
	}
}
