// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shared/infrastructure/persistence/postgres/ent/accessgroup"
	"shared/infrastructure/persistence/postgres/ent/predicate"
	"shared/infrastructure/persistence/postgres/ent/usersonaccessgroups"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessGroupUpdate is the builder for updating AccessGroup entities.
type AccessGroupUpdate struct {
	config
	hooks    []Hook
	mutation *AccessGroupMutation
}

// Where appends a list predicates to the AccessGroupUpdate builder.
func (agu *AccessGroupUpdate) Where(ps ...predicate.AccessGroup) *AccessGroupUpdate {
	agu.mutation.Where(ps...)
	return agu
}

// SetName sets the "name" field.
func (agu *AccessGroupUpdate) SetName(s string) *AccessGroupUpdate {
	agu.mutation.SetName(s)
	return agu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (agu *AccessGroupUpdate) SetNillableName(s *string) *AccessGroupUpdate {
	if s != nil {
		agu.SetName(*s)
	}
	return agu
}

// SetCreatedAt sets the "created_at" field.
func (agu *AccessGroupUpdate) SetCreatedAt(t time.Time) *AccessGroupUpdate {
	agu.mutation.SetCreatedAt(t)
	return agu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (agu *AccessGroupUpdate) SetNillableCreatedAt(t *time.Time) *AccessGroupUpdate {
	if t != nil {
		agu.SetCreatedAt(*t)
	}
	return agu
}

// SetUpdatedAt sets the "updated_at" field.
func (agu *AccessGroupUpdate) SetUpdatedAt(t time.Time) *AccessGroupUpdate {
	agu.mutation.SetUpdatedAt(t)
	return agu
}

// SetDeactivatedAt sets the "deactivated_at" field.
func (agu *AccessGroupUpdate) SetDeactivatedAt(t time.Time) *AccessGroupUpdate {
	agu.mutation.SetDeactivatedAt(t)
	return agu
}

// SetNillableDeactivatedAt sets the "deactivated_at" field if the given value is not nil.
func (agu *AccessGroupUpdate) SetNillableDeactivatedAt(t *time.Time) *AccessGroupUpdate {
	if t != nil {
		agu.SetDeactivatedAt(*t)
	}
	return agu
}

// ClearDeactivatedAt clears the value of the "deactivated_at" field.
func (agu *AccessGroupUpdate) ClearDeactivatedAt() *AccessGroupUpdate {
	agu.mutation.ClearDeactivatedAt()
	return agu
}

// AddUserIDs adds the "users" edge to the UsersOnAccessGroups entity by IDs.
func (agu *AccessGroupUpdate) AddUserIDs(ids ...int) *AccessGroupUpdate {
	agu.mutation.AddUserIDs(ids...)
	return agu
}

// AddUsers adds the "users" edges to the UsersOnAccessGroups entity.
func (agu *AccessGroupUpdate) AddUsers(u ...*UsersOnAccessGroups) *AccessGroupUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return agu.AddUserIDs(ids...)
}

// Mutation returns the AccessGroupMutation object of the builder.
func (agu *AccessGroupUpdate) Mutation() *AccessGroupMutation {
	return agu.mutation
}

// ClearUsers clears all "users" edges to the UsersOnAccessGroups entity.
func (agu *AccessGroupUpdate) ClearUsers() *AccessGroupUpdate {
	agu.mutation.ClearUsers()
	return agu
}

// RemoveUserIDs removes the "users" edge to UsersOnAccessGroups entities by IDs.
func (agu *AccessGroupUpdate) RemoveUserIDs(ids ...int) *AccessGroupUpdate {
	agu.mutation.RemoveUserIDs(ids...)
	return agu
}

// RemoveUsers removes "users" edges to UsersOnAccessGroups entities.
func (agu *AccessGroupUpdate) RemoveUsers(u ...*UsersOnAccessGroups) *AccessGroupUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return agu.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (agu *AccessGroupUpdate) Save(ctx context.Context) (int, error) {
	agu.defaults()
	return withHooks(ctx, agu.sqlSave, agu.mutation, agu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (agu *AccessGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := agu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (agu *AccessGroupUpdate) Exec(ctx context.Context) error {
	_, err := agu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (agu *AccessGroupUpdate) ExecX(ctx context.Context) {
	if err := agu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (agu *AccessGroupUpdate) defaults() {
	if _, ok := agu.mutation.UpdatedAt(); !ok {
		v := accessgroup.UpdateDefaultUpdatedAt()
		agu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (agu *AccessGroupUpdate) check() error {
	if v, ok := agu.mutation.Name(); ok {
		if err := accessgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccessGroup.name": %w`, err)}
		}
	}
	return nil
}

func (agu *AccessGroupUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := agu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(accessgroup.Table, accessgroup.Columns, sqlgraph.NewFieldSpec(accessgroup.FieldID, field.TypeInt))
	if ps := agu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := agu.mutation.Name(); ok {
		_spec.SetField(accessgroup.FieldName, field.TypeString, value)
	}
	if value, ok := agu.mutation.CreatedAt(); ok {
		_spec.SetField(accessgroup.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := agu.mutation.UpdatedAt(); ok {
		_spec.SetField(accessgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := agu.mutation.DeactivatedAt(); ok {
		_spec.SetField(accessgroup.FieldDeactivatedAt, field.TypeTime, value)
	}
	if agu.mutation.DeactivatedAtCleared() {
		_spec.ClearField(accessgroup.FieldDeactivatedAt, field.TypeTime)
	}
	if agu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accessgroup.UsersTable,
			Columns: []string{accessgroup.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := agu.mutation.RemovedUsersIDs(); len(nodes) > 0 && !agu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accessgroup.UsersTable,
			Columns: []string{accessgroup.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := agu.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accessgroup.UsersTable,
			Columns: []string{accessgroup.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, agu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accessgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	agu.mutation.done = true
	return n, nil
}

// AccessGroupUpdateOne is the builder for updating a single AccessGroup entity.
type AccessGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccessGroupMutation
}

// SetName sets the "name" field.
func (aguo *AccessGroupUpdateOne) SetName(s string) *AccessGroupUpdateOne {
	aguo.mutation.SetName(s)
	return aguo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (aguo *AccessGroupUpdateOne) SetNillableName(s *string) *AccessGroupUpdateOne {
	if s != nil {
		aguo.SetName(*s)
	}
	return aguo
}

// SetCreatedAt sets the "created_at" field.
func (aguo *AccessGroupUpdateOne) SetCreatedAt(t time.Time) *AccessGroupUpdateOne {
	aguo.mutation.SetCreatedAt(t)
	return aguo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aguo *AccessGroupUpdateOne) SetNillableCreatedAt(t *time.Time) *AccessGroupUpdateOne {
	if t != nil {
		aguo.SetCreatedAt(*t)
	}
	return aguo
}

// SetUpdatedAt sets the "updated_at" field.
func (aguo *AccessGroupUpdateOne) SetUpdatedAt(t time.Time) *AccessGroupUpdateOne {
	aguo.mutation.SetUpdatedAt(t)
	return aguo
}

// SetDeactivatedAt sets the "deactivated_at" field.
func (aguo *AccessGroupUpdateOne) SetDeactivatedAt(t time.Time) *AccessGroupUpdateOne {
	aguo.mutation.SetDeactivatedAt(t)
	return aguo
}

// SetNillableDeactivatedAt sets the "deactivated_at" field if the given value is not nil.
func (aguo *AccessGroupUpdateOne) SetNillableDeactivatedAt(t *time.Time) *AccessGroupUpdateOne {
	if t != nil {
		aguo.SetDeactivatedAt(*t)
	}
	return aguo
}

// ClearDeactivatedAt clears the value of the "deactivated_at" field.
func (aguo *AccessGroupUpdateOne) ClearDeactivatedAt() *AccessGroupUpdateOne {
	aguo.mutation.ClearDeactivatedAt()
	return aguo
}

// AddUserIDs adds the "users" edge to the UsersOnAccessGroups entity by IDs.
func (aguo *AccessGroupUpdateOne) AddUserIDs(ids ...int) *AccessGroupUpdateOne {
	aguo.mutation.AddUserIDs(ids...)
	return aguo
}

// AddUsers adds the "users" edges to the UsersOnAccessGroups entity.
func (aguo *AccessGroupUpdateOne) AddUsers(u ...*UsersOnAccessGroups) *AccessGroupUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return aguo.AddUserIDs(ids...)
}

// Mutation returns the AccessGroupMutation object of the builder.
func (aguo *AccessGroupUpdateOne) Mutation() *AccessGroupMutation {
	return aguo.mutation
}

// ClearUsers clears all "users" edges to the UsersOnAccessGroups entity.
func (aguo *AccessGroupUpdateOne) ClearUsers() *AccessGroupUpdateOne {
	aguo.mutation.ClearUsers()
	return aguo
}

// RemoveUserIDs removes the "users" edge to UsersOnAccessGroups entities by IDs.
func (aguo *AccessGroupUpdateOne) RemoveUserIDs(ids ...int) *AccessGroupUpdateOne {
	aguo.mutation.RemoveUserIDs(ids...)
	return aguo
}

// RemoveUsers removes "users" edges to UsersOnAccessGroups entities.
func (aguo *AccessGroupUpdateOne) RemoveUsers(u ...*UsersOnAccessGroups) *AccessGroupUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return aguo.RemoveUserIDs(ids...)
}

// Where appends a list predicates to the AccessGroupUpdate builder.
func (aguo *AccessGroupUpdateOne) Where(ps ...predicate.AccessGroup) *AccessGroupUpdateOne {
	aguo.mutation.Where(ps...)
	return aguo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aguo *AccessGroupUpdateOne) Select(field string, fields ...string) *AccessGroupUpdateOne {
	aguo.fields = append([]string{field}, fields...)
	return aguo
}

// Save executes the query and returns the updated AccessGroup entity.
func (aguo *AccessGroupUpdateOne) Save(ctx context.Context) (*AccessGroup, error) {
	aguo.defaults()
	return withHooks(ctx, aguo.sqlSave, aguo.mutation, aguo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aguo *AccessGroupUpdateOne) SaveX(ctx context.Context) *AccessGroup {
	node, err := aguo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aguo *AccessGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := aguo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aguo *AccessGroupUpdateOne) ExecX(ctx context.Context) {
	if err := aguo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aguo *AccessGroupUpdateOne) defaults() {
	if _, ok := aguo.mutation.UpdatedAt(); !ok {
		v := accessgroup.UpdateDefaultUpdatedAt()
		aguo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aguo *AccessGroupUpdateOne) check() error {
	if v, ok := aguo.mutation.Name(); ok {
		if err := accessgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccessGroup.name": %w`, err)}
		}
	}
	return nil
}

func (aguo *AccessGroupUpdateOne) sqlSave(ctx context.Context) (_node *AccessGroup, err error) {
	if err := aguo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accessgroup.Table, accessgroup.Columns, sqlgraph.NewFieldSpec(accessgroup.FieldID, field.TypeInt))
	id, ok := aguo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccessGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aguo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accessgroup.FieldID)
		for _, f := range fields {
			if !accessgroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accessgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aguo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aguo.mutation.Name(); ok {
		_spec.SetField(accessgroup.FieldName, field.TypeString, value)
	}
	if value, ok := aguo.mutation.CreatedAt(); ok {
		_spec.SetField(accessgroup.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := aguo.mutation.UpdatedAt(); ok {
		_spec.SetField(accessgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := aguo.mutation.DeactivatedAt(); ok {
		_spec.SetField(accessgroup.FieldDeactivatedAt, field.TypeTime, value)
	}
	if aguo.mutation.DeactivatedAtCleared() {
		_spec.ClearField(accessgroup.FieldDeactivatedAt, field.TypeTime)
	}
	if aguo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accessgroup.UsersTable,
			Columns: []string{accessgroup.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aguo.mutation.RemovedUsersIDs(); len(nodes) > 0 && !aguo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accessgroup.UsersTable,
			Columns: []string{accessgroup.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aguo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accessgroup.UsersTable,
			Columns: []string{accessgroup.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccessGroup{config: aguo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aguo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accessgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aguo.mutation.done = true
	return _node, nil
}
