// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"shared/infrastructure/persistence/postgres/ent/migrate"

	"shared/infrastructure/persistence/postgres/ent/accessgroup"
	"shared/infrastructure/persistence/postgres/ent/business"
	"shared/infrastructure/persistence/postgres/ent/user"
	"shared/infrastructure/persistence/postgres/ent/usersonaccessgroups"
	"shared/infrastructure/persistence/postgres/ent/userstatus"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AccessGroup is the client for interacting with the AccessGroup builders.
	AccessGroup *AccessGroupClient
	// Business is the client for interacting with the Business builders.
	Business *BusinessClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// UserStatus is the client for interacting with the UserStatus builders.
	UserStatus *UserStatusClient
	// UsersOnAccessGroups is the client for interacting with the UsersOnAccessGroups builders.
	UsersOnAccessGroups *UsersOnAccessGroupsClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AccessGroup = NewAccessGroupClient(c.config)
	c.Business = NewBusinessClient(c.config)
	c.User = NewUserClient(c.config)
	c.UserStatus = NewUserStatusClient(c.config)
	c.UsersOnAccessGroups = NewUsersOnAccessGroupsClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		AccessGroup:         NewAccessGroupClient(cfg),
		Business:            NewBusinessClient(cfg),
		User:                NewUserClient(cfg),
		UserStatus:          NewUserStatusClient(cfg),
		UsersOnAccessGroups: NewUsersOnAccessGroupsClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		AccessGroup:         NewAccessGroupClient(cfg),
		Business:            NewBusinessClient(cfg),
		User:                NewUserClient(cfg),
		UserStatus:          NewUserStatusClient(cfg),
		UsersOnAccessGroups: NewUsersOnAccessGroupsClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AccessGroup.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.AccessGroup.Use(hooks...)
	c.Business.Use(hooks...)
	c.User.Use(hooks...)
	c.UserStatus.Use(hooks...)
	c.UsersOnAccessGroups.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.AccessGroup.Intercept(interceptors...)
	c.Business.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
	c.UserStatus.Intercept(interceptors...)
	c.UsersOnAccessGroups.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AccessGroupMutation:
		return c.AccessGroup.mutate(ctx, m)
	case *BusinessMutation:
		return c.Business.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	case *UserStatusMutation:
		return c.UserStatus.mutate(ctx, m)
	case *UsersOnAccessGroupsMutation:
		return c.UsersOnAccessGroups.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AccessGroupClient is a client for the AccessGroup schema.
type AccessGroupClient struct {
	config
}

// NewAccessGroupClient returns a client for the AccessGroup from the given config.
func NewAccessGroupClient(c config) *AccessGroupClient {
	return &AccessGroupClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `accessgroup.Hooks(f(g(h())))`.
func (c *AccessGroupClient) Use(hooks ...Hook) {
	c.hooks.AccessGroup = append(c.hooks.AccessGroup, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `accessgroup.Intercept(f(g(h())))`.
func (c *AccessGroupClient) Intercept(interceptors ...Interceptor) {
	c.inters.AccessGroup = append(c.inters.AccessGroup, interceptors...)
}

// Create returns a builder for creating a AccessGroup entity.
func (c *AccessGroupClient) Create() *AccessGroupCreate {
	mutation := newAccessGroupMutation(c.config, OpCreate)
	return &AccessGroupCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AccessGroup entities.
func (c *AccessGroupClient) CreateBulk(builders ...*AccessGroupCreate) *AccessGroupCreateBulk {
	return &AccessGroupCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AccessGroupClient) MapCreateBulk(slice any, setFunc func(*AccessGroupCreate, int)) *AccessGroupCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AccessGroupCreateBulk{err: fmt.Errorf("calling to AccessGroupClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AccessGroupCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AccessGroupCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AccessGroup.
func (c *AccessGroupClient) Update() *AccessGroupUpdate {
	mutation := newAccessGroupMutation(c.config, OpUpdate)
	return &AccessGroupUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AccessGroupClient) UpdateOne(ag *AccessGroup) *AccessGroupUpdateOne {
	mutation := newAccessGroupMutation(c.config, OpUpdateOne, withAccessGroup(ag))
	return &AccessGroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AccessGroupClient) UpdateOneID(id int) *AccessGroupUpdateOne {
	mutation := newAccessGroupMutation(c.config, OpUpdateOne, withAccessGroupID(id))
	return &AccessGroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AccessGroup.
func (c *AccessGroupClient) Delete() *AccessGroupDelete {
	mutation := newAccessGroupMutation(c.config, OpDelete)
	return &AccessGroupDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AccessGroupClient) DeleteOne(ag *AccessGroup) *AccessGroupDeleteOne {
	return c.DeleteOneID(ag.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AccessGroupClient) DeleteOneID(id int) *AccessGroupDeleteOne {
	builder := c.Delete().Where(accessgroup.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AccessGroupDeleteOne{builder}
}

// Query returns a query builder for AccessGroup.
func (c *AccessGroupClient) Query() *AccessGroupQuery {
	return &AccessGroupQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAccessGroup},
		inters: c.Interceptors(),
	}
}

// Get returns a AccessGroup entity by its id.
func (c *AccessGroupClient) Get(ctx context.Context, id int) (*AccessGroup, error) {
	return c.Query().Where(accessgroup.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AccessGroupClient) GetX(ctx context.Context, id int) *AccessGroup {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUsers queries the users edge of a AccessGroup.
func (c *AccessGroupClient) QueryUsers(ag *AccessGroup) *UsersOnAccessGroupsQuery {
	query := (&UsersOnAccessGroupsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ag.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(accessgroup.Table, accessgroup.FieldID, id),
			sqlgraph.To(usersonaccessgroups.Table, usersonaccessgroups.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, accessgroup.UsersTable, accessgroup.UsersColumn),
		)
		fromV = sqlgraph.Neighbors(ag.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AccessGroupClient) Hooks() []Hook {
	return c.hooks.AccessGroup
}

// Interceptors returns the client interceptors.
func (c *AccessGroupClient) Interceptors() []Interceptor {
	return c.inters.AccessGroup
}

func (c *AccessGroupClient) mutate(ctx context.Context, m *AccessGroupMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AccessGroupCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AccessGroupUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AccessGroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AccessGroupDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AccessGroup mutation op: %q", m.Op())
	}
}

// BusinessClient is a client for the Business schema.
type BusinessClient struct {
	config
}

// NewBusinessClient returns a client for the Business from the given config.
func NewBusinessClient(c config) *BusinessClient {
	return &BusinessClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `business.Hooks(f(g(h())))`.
func (c *BusinessClient) Use(hooks ...Hook) {
	c.hooks.Business = append(c.hooks.Business, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `business.Intercept(f(g(h())))`.
func (c *BusinessClient) Intercept(interceptors ...Interceptor) {
	c.inters.Business = append(c.inters.Business, interceptors...)
}

// Create returns a builder for creating a Business entity.
func (c *BusinessClient) Create() *BusinessCreate {
	mutation := newBusinessMutation(c.config, OpCreate)
	return &BusinessCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Business entities.
func (c *BusinessClient) CreateBulk(builders ...*BusinessCreate) *BusinessCreateBulk {
	return &BusinessCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BusinessClient) MapCreateBulk(slice any, setFunc func(*BusinessCreate, int)) *BusinessCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BusinessCreateBulk{err: fmt.Errorf("calling to BusinessClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BusinessCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BusinessCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Business.
func (c *BusinessClient) Update() *BusinessUpdate {
	mutation := newBusinessMutation(c.config, OpUpdate)
	return &BusinessUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BusinessClient) UpdateOne(b *Business) *BusinessUpdateOne {
	mutation := newBusinessMutation(c.config, OpUpdateOne, withBusiness(b))
	return &BusinessUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BusinessClient) UpdateOneID(id int) *BusinessUpdateOne {
	mutation := newBusinessMutation(c.config, OpUpdateOne, withBusinessID(id))
	return &BusinessUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Business.
func (c *BusinessClient) Delete() *BusinessDelete {
	mutation := newBusinessMutation(c.config, OpDelete)
	return &BusinessDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BusinessClient) DeleteOne(b *Business) *BusinessDeleteOne {
	return c.DeleteOneID(b.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BusinessClient) DeleteOneID(id int) *BusinessDeleteOne {
	builder := c.Delete().Where(business.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BusinessDeleteOne{builder}
}

// Query returns a query builder for Business.
func (c *BusinessClient) Query() *BusinessQuery {
	return &BusinessQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBusiness},
		inters: c.Interceptors(),
	}
}

// Get returns a Business entity by its id.
func (c *BusinessClient) Get(ctx context.Context, id int) (*Business, error) {
	return c.Query().Where(business.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BusinessClient) GetX(ctx context.Context, id int) *Business {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUsers queries the users edge of a Business.
func (c *BusinessClient) QueryUsers(b *Business) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := b.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(business.Table, business.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, business.UsersTable, business.UsersColumn),
		)
		fromV = sqlgraph.Neighbors(b.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BusinessClient) Hooks() []Hook {
	return c.hooks.Business
}

// Interceptors returns the client interceptors.
func (c *BusinessClient) Interceptors() []Interceptor {
	return c.inters.Business
}

func (c *BusinessClient) mutate(ctx context.Context, m *BusinessMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BusinessCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BusinessUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BusinessUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BusinessDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Business mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uuid.UUID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uuid.UUID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uuid.UUID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uuid.UUID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryManager queries the manager edge of a User.
func (c *UserClient) QueryManager(u *User) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, user.ManagerTable, user.ManagerColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySubordinates queries the subordinates edge of a User.
func (c *UserClient) QuerySubordinates(u *User) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.SubordinatesTable, user.SubordinatesColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBusiness queries the business edge of a User.
func (c *UserClient) QueryBusiness(u *User) *BusinessQuery {
	query := (&BusinessClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(business.Table, business.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, user.BusinessTable, user.BusinessColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryStatus queries the status edge of a User.
func (c *UserClient) QueryStatus(u *User) *UserStatusQuery {
	query := (&UserStatusClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(userstatus.Table, userstatus.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, user.StatusTable, user.StatusColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAccessGroups queries the access_groups edge of a User.
func (c *UserClient) QueryAccessGroups(u *User) *UsersOnAccessGroupsQuery {
	query := (&UsersOnAccessGroupsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(usersonaccessgroups.Table, usersonaccessgroups.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.AccessGroupsTable, user.AccessGroupsColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// UserStatusClient is a client for the UserStatus schema.
type UserStatusClient struct {
	config
}

// NewUserStatusClient returns a client for the UserStatus from the given config.
func NewUserStatusClient(c config) *UserStatusClient {
	return &UserStatusClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `userstatus.Hooks(f(g(h())))`.
func (c *UserStatusClient) Use(hooks ...Hook) {
	c.hooks.UserStatus = append(c.hooks.UserStatus, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `userstatus.Intercept(f(g(h())))`.
func (c *UserStatusClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserStatus = append(c.inters.UserStatus, interceptors...)
}

// Create returns a builder for creating a UserStatus entity.
func (c *UserStatusClient) Create() *UserStatusCreate {
	mutation := newUserStatusMutation(c.config, OpCreate)
	return &UserStatusCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserStatus entities.
func (c *UserStatusClient) CreateBulk(builders ...*UserStatusCreate) *UserStatusCreateBulk {
	return &UserStatusCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserStatusClient) MapCreateBulk(slice any, setFunc func(*UserStatusCreate, int)) *UserStatusCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserStatusCreateBulk{err: fmt.Errorf("calling to UserStatusClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserStatusCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserStatusCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserStatus.
func (c *UserStatusClient) Update() *UserStatusUpdate {
	mutation := newUserStatusMutation(c.config, OpUpdate)
	return &UserStatusUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserStatusClient) UpdateOne(us *UserStatus) *UserStatusUpdateOne {
	mutation := newUserStatusMutation(c.config, OpUpdateOne, withUserStatus(us))
	return &UserStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserStatusClient) UpdateOneID(id int) *UserStatusUpdateOne {
	mutation := newUserStatusMutation(c.config, OpUpdateOne, withUserStatusID(id))
	return &UserStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserStatus.
func (c *UserStatusClient) Delete() *UserStatusDelete {
	mutation := newUserStatusMutation(c.config, OpDelete)
	return &UserStatusDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserStatusClient) DeleteOne(us *UserStatus) *UserStatusDeleteOne {
	return c.DeleteOneID(us.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserStatusClient) DeleteOneID(id int) *UserStatusDeleteOne {
	builder := c.Delete().Where(userstatus.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserStatusDeleteOne{builder}
}

// Query returns a query builder for UserStatus.
func (c *UserStatusClient) Query() *UserStatusQuery {
	return &UserStatusQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserStatus},
		inters: c.Interceptors(),
	}
}

// Get returns a UserStatus entity by its id.
func (c *UserStatusClient) Get(ctx context.Context, id int) (*UserStatus, error) {
	return c.Query().Where(userstatus.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserStatusClient) GetX(ctx context.Context, id int) *UserStatus {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUsers queries the users edge of a UserStatus.
func (c *UserStatusClient) QueryUsers(us *UserStatus) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := us.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(userstatus.Table, userstatus.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, userstatus.UsersTable, userstatus.UsersColumn),
		)
		fromV = sqlgraph.Neighbors(us.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserStatusClient) Hooks() []Hook {
	return c.hooks.UserStatus
}

// Interceptors returns the client interceptors.
func (c *UserStatusClient) Interceptors() []Interceptor {
	return c.inters.UserStatus
}

func (c *UserStatusClient) mutate(ctx context.Context, m *UserStatusMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserStatusCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserStatusUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserStatusDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserStatus mutation op: %q", m.Op())
	}
}

// UsersOnAccessGroupsClient is a client for the UsersOnAccessGroups schema.
type UsersOnAccessGroupsClient struct {
	config
}

// NewUsersOnAccessGroupsClient returns a client for the UsersOnAccessGroups from the given config.
func NewUsersOnAccessGroupsClient(c config) *UsersOnAccessGroupsClient {
	return &UsersOnAccessGroupsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `usersonaccessgroups.Hooks(f(g(h())))`.
func (c *UsersOnAccessGroupsClient) Use(hooks ...Hook) {
	c.hooks.UsersOnAccessGroups = append(c.hooks.UsersOnAccessGroups, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `usersonaccessgroups.Intercept(f(g(h())))`.
func (c *UsersOnAccessGroupsClient) Intercept(interceptors ...Interceptor) {
	c.inters.UsersOnAccessGroups = append(c.inters.UsersOnAccessGroups, interceptors...)
}

// Create returns a builder for creating a UsersOnAccessGroups entity.
func (c *UsersOnAccessGroupsClient) Create() *UsersOnAccessGroupsCreate {
	mutation := newUsersOnAccessGroupsMutation(c.config, OpCreate)
	return &UsersOnAccessGroupsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UsersOnAccessGroups entities.
func (c *UsersOnAccessGroupsClient) CreateBulk(builders ...*UsersOnAccessGroupsCreate) *UsersOnAccessGroupsCreateBulk {
	return &UsersOnAccessGroupsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UsersOnAccessGroupsClient) MapCreateBulk(slice any, setFunc func(*UsersOnAccessGroupsCreate, int)) *UsersOnAccessGroupsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UsersOnAccessGroupsCreateBulk{err: fmt.Errorf("calling to UsersOnAccessGroupsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UsersOnAccessGroupsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UsersOnAccessGroupsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UsersOnAccessGroups.
func (c *UsersOnAccessGroupsClient) Update() *UsersOnAccessGroupsUpdate {
	mutation := newUsersOnAccessGroupsMutation(c.config, OpUpdate)
	return &UsersOnAccessGroupsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UsersOnAccessGroupsClient) UpdateOne(uoag *UsersOnAccessGroups) *UsersOnAccessGroupsUpdateOne {
	mutation := newUsersOnAccessGroupsMutation(c.config, OpUpdateOne, withUsersOnAccessGroups(uoag))
	return &UsersOnAccessGroupsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UsersOnAccessGroupsClient) UpdateOneID(id int) *UsersOnAccessGroupsUpdateOne {
	mutation := newUsersOnAccessGroupsMutation(c.config, OpUpdateOne, withUsersOnAccessGroupsID(id))
	return &UsersOnAccessGroupsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UsersOnAccessGroups.
func (c *UsersOnAccessGroupsClient) Delete() *UsersOnAccessGroupsDelete {
	mutation := newUsersOnAccessGroupsMutation(c.config, OpDelete)
	return &UsersOnAccessGroupsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UsersOnAccessGroupsClient) DeleteOne(uoag *UsersOnAccessGroups) *UsersOnAccessGroupsDeleteOne {
	return c.DeleteOneID(uoag.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UsersOnAccessGroupsClient) DeleteOneID(id int) *UsersOnAccessGroupsDeleteOne {
	builder := c.Delete().Where(usersonaccessgroups.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UsersOnAccessGroupsDeleteOne{builder}
}

// Query returns a query builder for UsersOnAccessGroups.
func (c *UsersOnAccessGroupsClient) Query() *UsersOnAccessGroupsQuery {
	return &UsersOnAccessGroupsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUsersOnAccessGroups},
		inters: c.Interceptors(),
	}
}

// Get returns a UsersOnAccessGroups entity by its id.
func (c *UsersOnAccessGroupsClient) Get(ctx context.Context, id int) (*UsersOnAccessGroups, error) {
	return c.Query().Where(usersonaccessgroups.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UsersOnAccessGroupsClient) GetX(ctx context.Context, id int) *UsersOnAccessGroups {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a UsersOnAccessGroups.
func (c *UsersOnAccessGroupsClient) QueryUser(uoag *UsersOnAccessGroups) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := uoag.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(usersonaccessgroups.Table, usersonaccessgroups.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usersonaccessgroups.UserTable, usersonaccessgroups.UserColumn),
		)
		fromV = sqlgraph.Neighbors(uoag.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAccessGroup queries the access_group edge of a UsersOnAccessGroups.
func (c *UsersOnAccessGroupsClient) QueryAccessGroup(uoag *UsersOnAccessGroups) *AccessGroupQuery {
	query := (&AccessGroupClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := uoag.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(usersonaccessgroups.Table, usersonaccessgroups.FieldID, id),
			sqlgraph.To(accessgroup.Table, accessgroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usersonaccessgroups.AccessGroupTable, usersonaccessgroups.AccessGroupColumn),
		)
		fromV = sqlgraph.Neighbors(uoag.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UsersOnAccessGroupsClient) Hooks() []Hook {
	return c.hooks.UsersOnAccessGroups
}

// Interceptors returns the client interceptors.
func (c *UsersOnAccessGroupsClient) Interceptors() []Interceptor {
	return c.inters.UsersOnAccessGroups
}

func (c *UsersOnAccessGroupsClient) mutate(ctx context.Context, m *UsersOnAccessGroupsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UsersOnAccessGroupsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UsersOnAccessGroupsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UsersOnAccessGroupsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UsersOnAccessGroupsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UsersOnAccessGroups mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AccessGroup, Business, User, UserStatus, UsersOnAccessGroups []ent.Hook
	}
	inters struct {
		AccessGroup, Business, User, UserStatus, UsersOnAccessGroups []ent.Interceptor
	}
)
