// Code generated by ent, DO NOT EDIT.

package ent

import (
	"shared/infrastructure/persistence/postgres/ent/accessgroup"
	"shared/infrastructure/persistence/postgres/ent/business"
	"shared/infrastructure/persistence/postgres/ent/schema"
	"shared/infrastructure/persistence/postgres/ent/user"
	"shared/infrastructure/persistence/postgres/ent/usersonaccessgroups"
	"shared/infrastructure/persistence/postgres/ent/userstatus"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accessgroupFields := schema.AccessGroup{}.Fields()
	_ = accessgroupFields
	// accessgroupDescName is the schema descriptor for name field.
	accessgroupDescName := accessgroupFields[1].Descriptor()
	// accessgroup.NameValidator is a validator for the "name" field. It is called by the builders before save.
	accessgroup.NameValidator = accessgroupDescName.Validators[0].(func(string) error)
	// accessgroupDescCreatedAt is the schema descriptor for created_at field.
	accessgroupDescCreatedAt := accessgroupFields[2].Descriptor()
	// accessgroup.DefaultCreatedAt holds the default value on creation for the created_at field.
	accessgroup.DefaultCreatedAt = accessgroupDescCreatedAt.Default.(func() time.Time)
	// accessgroupDescUpdatedAt is the schema descriptor for updated_at field.
	accessgroupDescUpdatedAt := accessgroupFields[3].Descriptor()
	// accessgroup.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	accessgroup.DefaultUpdatedAt = accessgroupDescUpdatedAt.Default.(func() time.Time)
	// accessgroup.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	accessgroup.UpdateDefaultUpdatedAt = accessgroupDescUpdatedAt.UpdateDefault.(func() time.Time)
	// accessgroupDescID is the schema descriptor for id field.
	accessgroupDescID := accessgroupFields[0].Descriptor()
	// accessgroup.IDValidator is a validator for the "id" field. It is called by the builders before save.
	accessgroup.IDValidator = accessgroupDescID.Validators[0].(func(int) error)
	businessFields := schema.Business{}.Fields()
	_ = businessFields
	// businessDescName is the schema descriptor for name field.
	businessDescName := businessFields[1].Descriptor()
	// business.NameValidator is a validator for the "name" field. It is called by the builders before save.
	business.NameValidator = businessDescName.Validators[0].(func(string) error)
	// businessDescCreatedAt is the schema descriptor for created_at field.
	businessDescCreatedAt := businessFields[2].Descriptor()
	// business.DefaultCreatedAt holds the default value on creation for the created_at field.
	business.DefaultCreatedAt = businessDescCreatedAt.Default.(func() time.Time)
	// businessDescUpdatedAt is the schema descriptor for updated_at field.
	businessDescUpdatedAt := businessFields[3].Descriptor()
	// business.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	business.DefaultUpdatedAt = businessDescUpdatedAt.Default.(func() time.Time)
	// business.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	business.UpdateDefaultUpdatedAt = businessDescUpdatedAt.UpdateDefault.(func() time.Time)
	// businessDescID is the schema descriptor for id field.
	businessDescID := businessFields[0].Descriptor()
	// business.IDValidator is a validator for the "id" field. It is called by the builders before save.
	business.IDValidator = businessDescID.Validators[0].(func(int) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescIsManager is the schema descriptor for is_manager field.
	userDescIsManager := userFields[3].Descriptor()
	// user.DefaultIsManager holds the default value on creation for the is_manager field.
	user.DefaultIsManager = userDescIsManager.Default.(bool)
	// userDescPhotoURL is the schema descriptor for photo_url field.
	userDescPhotoURL := userFields[4].Descriptor()
	// user.PhotoURLValidator is a validator for the "photo_url" field. It is called by the builders before save.
	user.PhotoURLValidator = userDescPhotoURL.Validators[0].(func(string) error)
	// userDescDocument is the schema descriptor for document field.
	userDescDocument := userFields[5].Descriptor()
	// user.DocumentValidator is a validator for the "document" field. It is called by the builders before save.
	user.DocumentValidator = userDescDocument.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[6].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[10].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[11].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	userstatusFields := schema.UserStatus{}.Fields()
	_ = userstatusFields
	// userstatusDescExternalID is the schema descriptor for external_id field.
	userstatusDescExternalID := userstatusFields[1].Descriptor()
	// userstatus.ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	userstatus.ExternalIDValidator = userstatusDescExternalID.Validators[0].(func(string) error)
	// userstatusDescName is the schema descriptor for name field.
	userstatusDescName := userstatusFields[2].Descriptor()
	// userstatus.NameValidator is a validator for the "name" field. It is called by the builders before save.
	userstatus.NameValidator = userstatusDescName.Validators[0].(func(string) error)
	// userstatusDescCreatedAt is the schema descriptor for created_at field.
	userstatusDescCreatedAt := userstatusFields[3].Descriptor()
	// userstatus.DefaultCreatedAt holds the default value on creation for the created_at field.
	userstatus.DefaultCreatedAt = userstatusDescCreatedAt.Default.(func() time.Time)
	// userstatusDescUpdatedAt is the schema descriptor for updated_at field.
	userstatusDescUpdatedAt := userstatusFields[4].Descriptor()
	// userstatus.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userstatus.DefaultUpdatedAt = userstatusDescUpdatedAt.Default.(func() time.Time)
	// userstatus.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userstatus.UpdateDefaultUpdatedAt = userstatusDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userstatusDescID is the schema descriptor for id field.
	userstatusDescID := userstatusFields[0].Descriptor()
	// userstatus.IDValidator is a validator for the "id" field. It is called by the builders before save.
	userstatus.IDValidator = userstatusDescID.Validators[0].(func(int) error)
	usersonaccessgroupsFields := schema.UsersOnAccessGroups{}.Fields()
	_ = usersonaccessgroupsFields
	// usersonaccessgroupsDescCreatedAt is the schema descriptor for created_at field.
	usersonaccessgroupsDescCreatedAt := usersonaccessgroupsFields[2].Descriptor()
	// usersonaccessgroups.DefaultCreatedAt holds the default value on creation for the created_at field.
	usersonaccessgroups.DefaultCreatedAt = usersonaccessgroupsDescCreatedAt.Default.(func() time.Time)
	// usersonaccessgroupsDescUpdatedAt is the schema descriptor for updated_at field.
	usersonaccessgroupsDescUpdatedAt := usersonaccessgroupsFields[3].Descriptor()
	// usersonaccessgroups.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	usersonaccessgroups.DefaultUpdatedAt = usersonaccessgroupsDescUpdatedAt.Default.(func() time.Time)
	// usersonaccessgroups.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	usersonaccessgroups.UpdateDefaultUpdatedAt = usersonaccessgroupsDescUpdatedAt.UpdateDefault.(func() time.Time)
}
