// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shared/infrastructure/persistence/postgres/ent/predicate"
	"shared/infrastructure/persistence/postgres/ent/user"
	"shared/infrastructure/persistence/postgres/ent/userstatus"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserStatusUpdate is the builder for updating UserStatus entities.
type UserStatusUpdate struct {
	config
	hooks    []Hook
	mutation *UserStatusMutation
}

// Where appends a list predicates to the UserStatusUpdate builder.
func (usu *UserStatusUpdate) Where(ps ...predicate.UserStatus) *UserStatusUpdate {
	usu.mutation.Where(ps...)
	return usu
}

// SetExternalID sets the "external_id" field.
func (usu *UserStatusUpdate) SetExternalID(s string) *UserStatusUpdate {
	usu.mutation.SetExternalID(s)
	return usu
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (usu *UserStatusUpdate) SetNillableExternalID(s *string) *UserStatusUpdate {
	if s != nil {
		usu.SetExternalID(*s)
	}
	return usu
}

// SetName sets the "name" field.
func (usu *UserStatusUpdate) SetName(s string) *UserStatusUpdate {
	usu.mutation.SetName(s)
	return usu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (usu *UserStatusUpdate) SetNillableName(s *string) *UserStatusUpdate {
	if s != nil {
		usu.SetName(*s)
	}
	return usu
}

// SetCreatedAt sets the "created_at" field.
func (usu *UserStatusUpdate) SetCreatedAt(t time.Time) *UserStatusUpdate {
	usu.mutation.SetCreatedAt(t)
	return usu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (usu *UserStatusUpdate) SetNillableCreatedAt(t *time.Time) *UserStatusUpdate {
	if t != nil {
		usu.SetCreatedAt(*t)
	}
	return usu
}

// SetUpdatedAt sets the "updated_at" field.
func (usu *UserStatusUpdate) SetUpdatedAt(t time.Time) *UserStatusUpdate {
	usu.mutation.SetUpdatedAt(t)
	return usu
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (usu *UserStatusUpdate) AddUserIDs(ids ...uuid.UUID) *UserStatusUpdate {
	usu.mutation.AddUserIDs(ids...)
	return usu
}

// AddUsers adds the "users" edges to the User entity.
func (usu *UserStatusUpdate) AddUsers(u ...*User) *UserStatusUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return usu.AddUserIDs(ids...)
}

// Mutation returns the UserStatusMutation object of the builder.
func (usu *UserStatusUpdate) Mutation() *UserStatusMutation {
	return usu.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (usu *UserStatusUpdate) ClearUsers() *UserStatusUpdate {
	usu.mutation.ClearUsers()
	return usu
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (usu *UserStatusUpdate) RemoveUserIDs(ids ...uuid.UUID) *UserStatusUpdate {
	usu.mutation.RemoveUserIDs(ids...)
	return usu
}

// RemoveUsers removes "users" edges to User entities.
func (usu *UserStatusUpdate) RemoveUsers(u ...*User) *UserStatusUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return usu.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (usu *UserStatusUpdate) Save(ctx context.Context) (int, error) {
	usu.defaults()
	return withHooks(ctx, usu.sqlSave, usu.mutation, usu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (usu *UserStatusUpdate) SaveX(ctx context.Context) int {
	affected, err := usu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (usu *UserStatusUpdate) Exec(ctx context.Context) error {
	_, err := usu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usu *UserStatusUpdate) ExecX(ctx context.Context) {
	if err := usu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (usu *UserStatusUpdate) defaults() {
	if _, ok := usu.mutation.UpdatedAt(); !ok {
		v := userstatus.UpdateDefaultUpdatedAt()
		usu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (usu *UserStatusUpdate) check() error {
	if v, ok := usu.mutation.ExternalID(); ok {
		if err := userstatus.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "UserStatus.external_id": %w`, err)}
		}
	}
	if v, ok := usu.mutation.Name(); ok {
		if err := userstatus.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserStatus.name": %w`, err)}
		}
	}
	return nil
}

func (usu *UserStatusUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := usu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(userstatus.Table, userstatus.Columns, sqlgraph.NewFieldSpec(userstatus.FieldID, field.TypeInt))
	if ps := usu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := usu.mutation.ExternalID(); ok {
		_spec.SetField(userstatus.FieldExternalID, field.TypeString, value)
	}
	if value, ok := usu.mutation.Name(); ok {
		_spec.SetField(userstatus.FieldName, field.TypeString, value)
	}
	if value, ok := usu.mutation.CreatedAt(); ok {
		_spec.SetField(userstatus.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := usu.mutation.UpdatedAt(); ok {
		_spec.SetField(userstatus.FieldUpdatedAt, field.TypeTime, value)
	}
	if usu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userstatus.UsersTable,
			Columns: []string{userstatus.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := usu.mutation.RemovedUsersIDs(); len(nodes) > 0 && !usu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userstatus.UsersTable,
			Columns: []string{userstatus.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := usu.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userstatus.UsersTable,
			Columns: []string{userstatus.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, usu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userstatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	usu.mutation.done = true
	return n, nil
}

// UserStatusUpdateOne is the builder for updating a single UserStatus entity.
type UserStatusUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserStatusMutation
}

// SetExternalID sets the "external_id" field.
func (usuo *UserStatusUpdateOne) SetExternalID(s string) *UserStatusUpdateOne {
	usuo.mutation.SetExternalID(s)
	return usuo
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (usuo *UserStatusUpdateOne) SetNillableExternalID(s *string) *UserStatusUpdateOne {
	if s != nil {
		usuo.SetExternalID(*s)
	}
	return usuo
}

// SetName sets the "name" field.
func (usuo *UserStatusUpdateOne) SetName(s string) *UserStatusUpdateOne {
	usuo.mutation.SetName(s)
	return usuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (usuo *UserStatusUpdateOne) SetNillableName(s *string) *UserStatusUpdateOne {
	if s != nil {
		usuo.SetName(*s)
	}
	return usuo
}

// SetCreatedAt sets the "created_at" field.
func (usuo *UserStatusUpdateOne) SetCreatedAt(t time.Time) *UserStatusUpdateOne {
	usuo.mutation.SetCreatedAt(t)
	return usuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (usuo *UserStatusUpdateOne) SetNillableCreatedAt(t *time.Time) *UserStatusUpdateOne {
	if t != nil {
		usuo.SetCreatedAt(*t)
	}
	return usuo
}

// SetUpdatedAt sets the "updated_at" field.
func (usuo *UserStatusUpdateOne) SetUpdatedAt(t time.Time) *UserStatusUpdateOne {
	usuo.mutation.SetUpdatedAt(t)
	return usuo
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (usuo *UserStatusUpdateOne) AddUserIDs(ids ...uuid.UUID) *UserStatusUpdateOne {
	usuo.mutation.AddUserIDs(ids...)
	return usuo
}

// AddUsers adds the "users" edges to the User entity.
func (usuo *UserStatusUpdateOne) AddUsers(u ...*User) *UserStatusUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return usuo.AddUserIDs(ids...)
}

// Mutation returns the UserStatusMutation object of the builder.
func (usuo *UserStatusUpdateOne) Mutation() *UserStatusMutation {
	return usuo.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (usuo *UserStatusUpdateOne) ClearUsers() *UserStatusUpdateOne {
	usuo.mutation.ClearUsers()
	return usuo
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (usuo *UserStatusUpdateOne) RemoveUserIDs(ids ...uuid.UUID) *UserStatusUpdateOne {
	usuo.mutation.RemoveUserIDs(ids...)
	return usuo
}

// RemoveUsers removes "users" edges to User entities.
func (usuo *UserStatusUpdateOne) RemoveUsers(u ...*User) *UserStatusUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return usuo.RemoveUserIDs(ids...)
}

// Where appends a list predicates to the UserStatusUpdate builder.
func (usuo *UserStatusUpdateOne) Where(ps ...predicate.UserStatus) *UserStatusUpdateOne {
	usuo.mutation.Where(ps...)
	return usuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (usuo *UserStatusUpdateOne) Select(field string, fields ...string) *UserStatusUpdateOne {
	usuo.fields = append([]string{field}, fields...)
	return usuo
}

// Save executes the query and returns the updated UserStatus entity.
func (usuo *UserStatusUpdateOne) Save(ctx context.Context) (*UserStatus, error) {
	usuo.defaults()
	return withHooks(ctx, usuo.sqlSave, usuo.mutation, usuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (usuo *UserStatusUpdateOne) SaveX(ctx context.Context) *UserStatus {
	node, err := usuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (usuo *UserStatusUpdateOne) Exec(ctx context.Context) error {
	_, err := usuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usuo *UserStatusUpdateOne) ExecX(ctx context.Context) {
	if err := usuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (usuo *UserStatusUpdateOne) defaults() {
	if _, ok := usuo.mutation.UpdatedAt(); !ok {
		v := userstatus.UpdateDefaultUpdatedAt()
		usuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (usuo *UserStatusUpdateOne) check() error {
	if v, ok := usuo.mutation.ExternalID(); ok {
		if err := userstatus.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "UserStatus.external_id": %w`, err)}
		}
	}
	if v, ok := usuo.mutation.Name(); ok {
		if err := userstatus.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserStatus.name": %w`, err)}
		}
	}
	return nil
}

func (usuo *UserStatusUpdateOne) sqlSave(ctx context.Context) (_node *UserStatus, err error) {
	if err := usuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userstatus.Table, userstatus.Columns, sqlgraph.NewFieldSpec(userstatus.FieldID, field.TypeInt))
	id, ok := usuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserStatus.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := usuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userstatus.FieldID)
		for _, f := range fields {
			if !userstatus.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userstatus.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := usuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := usuo.mutation.ExternalID(); ok {
		_spec.SetField(userstatus.FieldExternalID, field.TypeString, value)
	}
	if value, ok := usuo.mutation.Name(); ok {
		_spec.SetField(userstatus.FieldName, field.TypeString, value)
	}
	if value, ok := usuo.mutation.CreatedAt(); ok {
		_spec.SetField(userstatus.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := usuo.mutation.UpdatedAt(); ok {
		_spec.SetField(userstatus.FieldUpdatedAt, field.TypeTime, value)
	}
	if usuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userstatus.UsersTable,
			Columns: []string{userstatus.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := usuo.mutation.RemovedUsersIDs(); len(nodes) > 0 && !usuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userstatus.UsersTable,
			Columns: []string{userstatus.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := usuo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userstatus.UsersTable,
			Columns: []string{userstatus.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserStatus{config: usuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, usuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userstatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	usuo.mutation.done = true
	return _node, nil
}
