// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"shared/infrastructure/persistence/postgres/ent/accessgroup"
	"shared/infrastructure/persistence/postgres/ent/user"
	"shared/infrastructure/persistence/postgres/ent/usersonaccessgroups"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// UsersOnAccessGroups is the model entity for the UsersOnAccessGroups schema.
type UsersOnAccessGroups struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// AccessGroupID holds the value of the "access_group_id" field.
	AccessGroupID int `json:"access_group_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsersOnAccessGroupsQuery when eager-loading is set.
	Edges        UsersOnAccessGroupsEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsersOnAccessGroupsEdges holds the relations/edges for other nodes in the graph.
type UsersOnAccessGroupsEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// AccessGroup holds the value of the access_group edge.
	AccessGroup *AccessGroup `json:"access_group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsersOnAccessGroupsEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// AccessGroupOrErr returns the AccessGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsersOnAccessGroupsEdges) AccessGroupOrErr() (*AccessGroup, error) {
	if e.AccessGroup != nil {
		return e.AccessGroup, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: accessgroup.Label}
	}
	return nil, &NotLoadedError{edge: "access_group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsersOnAccessGroups) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usersonaccessgroups.FieldID, usersonaccessgroups.FieldAccessGroupID:
			values[i] = new(sql.NullInt64)
		case usersonaccessgroups.FieldCreatedAt, usersonaccessgroups.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case usersonaccessgroups.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsersOnAccessGroups fields.
func (uoag *UsersOnAccessGroups) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usersonaccessgroups.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			uoag.ID = int(value.Int64)
		case usersonaccessgroups.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				uoag.UserID = *value
			}
		case usersonaccessgroups.FieldAccessGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field access_group_id", values[i])
			} else if value.Valid {
				uoag.AccessGroupID = int(value.Int64)
			}
		case usersonaccessgroups.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				uoag.CreatedAt = value.Time
			}
		case usersonaccessgroups.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				uoag.UpdatedAt = value.Time
			}
		default:
			uoag.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsersOnAccessGroups.
// This includes values selected through modifiers, order, etc.
func (uoag *UsersOnAccessGroups) Value(name string) (ent.Value, error) {
	return uoag.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UsersOnAccessGroups entity.
func (uoag *UsersOnAccessGroups) QueryUser() *UserQuery {
	return NewUsersOnAccessGroupsClient(uoag.config).QueryUser(uoag)
}

// QueryAccessGroup queries the "access_group" edge of the UsersOnAccessGroups entity.
func (uoag *UsersOnAccessGroups) QueryAccessGroup() *AccessGroupQuery {
	return NewUsersOnAccessGroupsClient(uoag.config).QueryAccessGroup(uoag)
}

// Update returns a builder for updating this UsersOnAccessGroups.
// Note that you need to call UsersOnAccessGroups.Unwrap() before calling this method if this UsersOnAccessGroups
// was returned from a transaction, and the transaction was committed or rolled back.
func (uoag *UsersOnAccessGroups) Update() *UsersOnAccessGroupsUpdateOne {
	return NewUsersOnAccessGroupsClient(uoag.config).UpdateOne(uoag)
}

// Unwrap unwraps the UsersOnAccessGroups entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (uoag *UsersOnAccessGroups) Unwrap() *UsersOnAccessGroups {
	_tx, ok := uoag.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsersOnAccessGroups is not a transactional entity")
	}
	uoag.config.driver = _tx.drv
	return uoag
}

// String implements the fmt.Stringer.
func (uoag *UsersOnAccessGroups) String() string {
	var builder strings.Builder
	builder.WriteString("UsersOnAccessGroups(")
	builder.WriteString(fmt.Sprintf("id=%v, ", uoag.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", uoag.UserID))
	builder.WriteString(", ")
	builder.WriteString("access_group_id=")
	builder.WriteString(fmt.Sprintf("%v", uoag.AccessGroupID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(uoag.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(uoag.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UsersOnAccessGroupsSlice is a parsable slice of UsersOnAccessGroups.
type UsersOnAccessGroupsSlice []*UsersOnAccessGroups
