// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"shared/infrastructure/persistence/postgres/ent/predicate"
	"shared/infrastructure/persistence/postgres/ent/userstatus"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserStatusDelete is the builder for deleting a UserStatus entity.
type UserStatusDelete struct {
	config
	hooks    []Hook
	mutation *UserStatusMutation
}

// Where appends a list predicates to the UserStatusDelete builder.
func (usd *UserStatusDelete) Where(ps ...predicate.UserStatus) *UserStatusDelete {
	usd.mutation.Where(ps...)
	return usd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (usd *UserStatusDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, usd.sqlExec, usd.mutation, usd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (usd *UserStatusDelete) ExecX(ctx context.Context) int {
	n, err := usd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (usd *UserStatusDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userstatus.Table, sqlgraph.NewFieldSpec(userstatus.FieldID, field.TypeInt))
	if ps := usd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, usd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	usd.mutation.done = true
	return affected, err
}

// UserStatusDeleteOne is the builder for deleting a single UserStatus entity.
type UserStatusDeleteOne struct {
	usd *UserStatusDelete
}

// Where appends a list predicates to the UserStatusDelete builder.
func (usdo *UserStatusDeleteOne) Where(ps ...predicate.UserStatus) *UserStatusDeleteOne {
	usdo.usd.mutation.Where(ps...)
	return usdo
}

// Exec executes the deletion query.
func (usdo *UserStatusDeleteOne) Exec(ctx context.Context) error {
	n, err := usdo.usd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userstatus.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (usdo *UserStatusDeleteOne) ExecX(ctx context.Context) {
	if err := usdo.Exec(ctx); err != nil {
		panic(err)
	}
}
