// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"shared/infrastructure/persistence/postgres/ent/accessgroup"
	"shared/infrastructure/persistence/postgres/ent/predicate"
	"shared/infrastructure/persistence/postgres/ent/user"
	"shared/infrastructure/persistence/postgres/ent/usersonaccessgroups"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UsersOnAccessGroupsQuery is the builder for querying UsersOnAccessGroups entities.
type UsersOnAccessGroupsQuery struct {
	config
	ctx             *QueryContext
	order           []usersonaccessgroups.OrderOption
	inters          []Interceptor
	predicates      []predicate.UsersOnAccessGroups
	withUser        *UserQuery
	withAccessGroup *AccessGroupQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UsersOnAccessGroupsQuery builder.
func (uoagq *UsersOnAccessGroupsQuery) Where(ps ...predicate.UsersOnAccessGroups) *UsersOnAccessGroupsQuery {
	uoagq.predicates = append(uoagq.predicates, ps...)
	return uoagq
}

// Limit the number of records to be returned by this query.
func (uoagq *UsersOnAccessGroupsQuery) Limit(limit int) *UsersOnAccessGroupsQuery {
	uoagq.ctx.Limit = &limit
	return uoagq
}

// Offset to start from.
func (uoagq *UsersOnAccessGroupsQuery) Offset(offset int) *UsersOnAccessGroupsQuery {
	uoagq.ctx.Offset = &offset
	return uoagq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uoagq *UsersOnAccessGroupsQuery) Unique(unique bool) *UsersOnAccessGroupsQuery {
	uoagq.ctx.Unique = &unique
	return uoagq
}

// Order specifies how the records should be ordered.
func (uoagq *UsersOnAccessGroupsQuery) Order(o ...usersonaccessgroups.OrderOption) *UsersOnAccessGroupsQuery {
	uoagq.order = append(uoagq.order, o...)
	return uoagq
}

// QueryUser chains the current query on the "user" edge.
func (uoagq *UsersOnAccessGroupsQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: uoagq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uoagq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uoagq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usersonaccessgroups.Table, usersonaccessgroups.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usersonaccessgroups.UserTable, usersonaccessgroups.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(uoagq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAccessGroup chains the current query on the "access_group" edge.
func (uoagq *UsersOnAccessGroupsQuery) QueryAccessGroup() *AccessGroupQuery {
	query := (&AccessGroupClient{config: uoagq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uoagq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uoagq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usersonaccessgroups.Table, usersonaccessgroups.FieldID, selector),
			sqlgraph.To(accessgroup.Table, accessgroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usersonaccessgroups.AccessGroupTable, usersonaccessgroups.AccessGroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(uoagq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UsersOnAccessGroups entity from the query.
// Returns a *NotFoundError when no UsersOnAccessGroups was found.
func (uoagq *UsersOnAccessGroupsQuery) First(ctx context.Context) (*UsersOnAccessGroups, error) {
	nodes, err := uoagq.Limit(1).All(setContextOp(ctx, uoagq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usersonaccessgroups.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uoagq *UsersOnAccessGroupsQuery) FirstX(ctx context.Context) *UsersOnAccessGroups {
	node, err := uoagq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UsersOnAccessGroups ID from the query.
// Returns a *NotFoundError when no UsersOnAccessGroups ID was found.
func (uoagq *UsersOnAccessGroupsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uoagq.Limit(1).IDs(setContextOp(ctx, uoagq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usersonaccessgroups.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uoagq *UsersOnAccessGroupsQuery) FirstIDX(ctx context.Context) int {
	id, err := uoagq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UsersOnAccessGroups entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UsersOnAccessGroups entity is found.
// Returns a *NotFoundError when no UsersOnAccessGroups entities are found.
func (uoagq *UsersOnAccessGroupsQuery) Only(ctx context.Context) (*UsersOnAccessGroups, error) {
	nodes, err := uoagq.Limit(2).All(setContextOp(ctx, uoagq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usersonaccessgroups.Label}
	default:
		return nil, &NotSingularError{usersonaccessgroups.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uoagq *UsersOnAccessGroupsQuery) OnlyX(ctx context.Context) *UsersOnAccessGroups {
	node, err := uoagq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UsersOnAccessGroups ID in the query.
// Returns a *NotSingularError when more than one UsersOnAccessGroups ID is found.
// Returns a *NotFoundError when no entities are found.
func (uoagq *UsersOnAccessGroupsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uoagq.Limit(2).IDs(setContextOp(ctx, uoagq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usersonaccessgroups.Label}
	default:
		err = &NotSingularError{usersonaccessgroups.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uoagq *UsersOnAccessGroupsQuery) OnlyIDX(ctx context.Context) int {
	id, err := uoagq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UsersOnAccessGroupsSlice.
func (uoagq *UsersOnAccessGroupsQuery) All(ctx context.Context) ([]*UsersOnAccessGroups, error) {
	ctx = setContextOp(ctx, uoagq.ctx, "All")
	if err := uoagq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UsersOnAccessGroups, *UsersOnAccessGroupsQuery]()
	return withInterceptors[[]*UsersOnAccessGroups](ctx, uoagq, qr, uoagq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uoagq *UsersOnAccessGroupsQuery) AllX(ctx context.Context) []*UsersOnAccessGroups {
	nodes, err := uoagq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UsersOnAccessGroups IDs.
func (uoagq *UsersOnAccessGroupsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if uoagq.ctx.Unique == nil && uoagq.path != nil {
		uoagq.Unique(true)
	}
	ctx = setContextOp(ctx, uoagq.ctx, "IDs")
	if err = uoagq.Select(usersonaccessgroups.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uoagq *UsersOnAccessGroupsQuery) IDsX(ctx context.Context) []int {
	ids, err := uoagq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uoagq *UsersOnAccessGroupsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uoagq.ctx, "Count")
	if err := uoagq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uoagq, querierCount[*UsersOnAccessGroupsQuery](), uoagq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uoagq *UsersOnAccessGroupsQuery) CountX(ctx context.Context) int {
	count, err := uoagq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uoagq *UsersOnAccessGroupsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uoagq.ctx, "Exist")
	switch _, err := uoagq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uoagq *UsersOnAccessGroupsQuery) ExistX(ctx context.Context) bool {
	exist, err := uoagq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UsersOnAccessGroupsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uoagq *UsersOnAccessGroupsQuery) Clone() *UsersOnAccessGroupsQuery {
	if uoagq == nil {
		return nil
	}
	return &UsersOnAccessGroupsQuery{
		config:          uoagq.config,
		ctx:             uoagq.ctx.Clone(),
		order:           append([]usersonaccessgroups.OrderOption{}, uoagq.order...),
		inters:          append([]Interceptor{}, uoagq.inters...),
		predicates:      append([]predicate.UsersOnAccessGroups{}, uoagq.predicates...),
		withUser:        uoagq.withUser.Clone(),
		withAccessGroup: uoagq.withAccessGroup.Clone(),
		// clone intermediate query.
		sql:  uoagq.sql.Clone(),
		path: uoagq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (uoagq *UsersOnAccessGroupsQuery) WithUser(opts ...func(*UserQuery)) *UsersOnAccessGroupsQuery {
	query := (&UserClient{config: uoagq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	uoagq.withUser = query
	return uoagq
}

// WithAccessGroup tells the query-builder to eager-load the nodes that are connected to
// the "access_group" edge. The optional arguments are used to configure the query builder of the edge.
func (uoagq *UsersOnAccessGroupsQuery) WithAccessGroup(opts ...func(*AccessGroupQuery)) *UsersOnAccessGroupsQuery {
	query := (&AccessGroupClient{config: uoagq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	uoagq.withAccessGroup = query
	return uoagq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UsersOnAccessGroups.Query().
//		GroupBy(usersonaccessgroups.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uoagq *UsersOnAccessGroupsQuery) GroupBy(field string, fields ...string) *UsersOnAccessGroupsGroupBy {
	uoagq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UsersOnAccessGroupsGroupBy{build: uoagq}
	grbuild.flds = &uoagq.ctx.Fields
	grbuild.label = usersonaccessgroups.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.UsersOnAccessGroups.Query().
//		Select(usersonaccessgroups.FieldUserID).
//		Scan(ctx, &v)
func (uoagq *UsersOnAccessGroupsQuery) Select(fields ...string) *UsersOnAccessGroupsSelect {
	uoagq.ctx.Fields = append(uoagq.ctx.Fields, fields...)
	sbuild := &UsersOnAccessGroupsSelect{UsersOnAccessGroupsQuery: uoagq}
	sbuild.label = usersonaccessgroups.Label
	sbuild.flds, sbuild.scan = &uoagq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UsersOnAccessGroupsSelect configured with the given aggregations.
func (uoagq *UsersOnAccessGroupsQuery) Aggregate(fns ...AggregateFunc) *UsersOnAccessGroupsSelect {
	return uoagq.Select().Aggregate(fns...)
}

func (uoagq *UsersOnAccessGroupsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uoagq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uoagq); err != nil {
				return err
			}
		}
	}
	for _, f := range uoagq.ctx.Fields {
		if !usersonaccessgroups.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uoagq.path != nil {
		prev, err := uoagq.path(ctx)
		if err != nil {
			return err
		}
		uoagq.sql = prev
	}
	return nil
}

func (uoagq *UsersOnAccessGroupsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UsersOnAccessGroups, error) {
	var (
		nodes       = []*UsersOnAccessGroups{}
		_spec       = uoagq.querySpec()
		loadedTypes = [2]bool{
			uoagq.withUser != nil,
			uoagq.withAccessGroup != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UsersOnAccessGroups).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UsersOnAccessGroups{config: uoagq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uoagq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := uoagq.withUser; query != nil {
		if err := uoagq.loadUser(ctx, query, nodes, nil,
			func(n *UsersOnAccessGroups, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := uoagq.withAccessGroup; query != nil {
		if err := uoagq.loadAccessGroup(ctx, query, nodes, nil,
			func(n *UsersOnAccessGroups, e *AccessGroup) { n.Edges.AccessGroup = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (uoagq *UsersOnAccessGroupsQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UsersOnAccessGroups, init func(*UsersOnAccessGroups), assign func(*UsersOnAccessGroups, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*UsersOnAccessGroups)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (uoagq *UsersOnAccessGroupsQuery) loadAccessGroup(ctx context.Context, query *AccessGroupQuery, nodes []*UsersOnAccessGroups, init func(*UsersOnAccessGroups), assign func(*UsersOnAccessGroups, *AccessGroup)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*UsersOnAccessGroups)
	for i := range nodes {
		fk := nodes[i].AccessGroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(accessgroup.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "access_group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (uoagq *UsersOnAccessGroupsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uoagq.querySpec()
	_spec.Node.Columns = uoagq.ctx.Fields
	if len(uoagq.ctx.Fields) > 0 {
		_spec.Unique = uoagq.ctx.Unique != nil && *uoagq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uoagq.driver, _spec)
}

func (uoagq *UsersOnAccessGroupsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(usersonaccessgroups.Table, usersonaccessgroups.Columns, sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt))
	_spec.From = uoagq.sql
	if unique := uoagq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uoagq.path != nil {
		_spec.Unique = true
	}
	if fields := uoagq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersonaccessgroups.FieldID)
		for i := range fields {
			if fields[i] != usersonaccessgroups.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if uoagq.withUser != nil {
			_spec.Node.AddColumnOnce(usersonaccessgroups.FieldUserID)
		}
		if uoagq.withAccessGroup != nil {
			_spec.Node.AddColumnOnce(usersonaccessgroups.FieldAccessGroupID)
		}
	}
	if ps := uoagq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uoagq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uoagq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uoagq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uoagq *UsersOnAccessGroupsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uoagq.driver.Dialect())
	t1 := builder.Table(usersonaccessgroups.Table)
	columns := uoagq.ctx.Fields
	if len(columns) == 0 {
		columns = usersonaccessgroups.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uoagq.sql != nil {
		selector = uoagq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uoagq.ctx.Unique != nil && *uoagq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uoagq.predicates {
		p(selector)
	}
	for _, p := range uoagq.order {
		p(selector)
	}
	if offset := uoagq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uoagq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UsersOnAccessGroupsGroupBy is the group-by builder for UsersOnAccessGroups entities.
type UsersOnAccessGroupsGroupBy struct {
	selector
	build *UsersOnAccessGroupsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uoaggb *UsersOnAccessGroupsGroupBy) Aggregate(fns ...AggregateFunc) *UsersOnAccessGroupsGroupBy {
	uoaggb.fns = append(uoaggb.fns, fns...)
	return uoaggb
}

// Scan applies the selector query and scans the result into the given value.
func (uoaggb *UsersOnAccessGroupsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uoaggb.build.ctx, "GroupBy")
	if err := uoaggb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UsersOnAccessGroupsQuery, *UsersOnAccessGroupsGroupBy](ctx, uoaggb.build, uoaggb, uoaggb.build.inters, v)
}

func (uoaggb *UsersOnAccessGroupsGroupBy) sqlScan(ctx context.Context, root *UsersOnAccessGroupsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uoaggb.fns))
	for _, fn := range uoaggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uoaggb.flds)+len(uoaggb.fns))
		for _, f := range *uoaggb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uoaggb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uoaggb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UsersOnAccessGroupsSelect is the builder for selecting fields of UsersOnAccessGroups entities.
type UsersOnAccessGroupsSelect struct {
	*UsersOnAccessGroupsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uoags *UsersOnAccessGroupsSelect) Aggregate(fns ...AggregateFunc) *UsersOnAccessGroupsSelect {
	uoags.fns = append(uoags.fns, fns...)
	return uoags
}

// Scan applies the selector query and scans the result into the given value.
func (uoags *UsersOnAccessGroupsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uoags.ctx, "Select")
	if err := uoags.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UsersOnAccessGroupsQuery, *UsersOnAccessGroupsSelect](ctx, uoags.UsersOnAccessGroupsQuery, uoags, uoags.inters, v)
}

func (uoags *UsersOnAccessGroupsSelect) sqlScan(ctx context.Context, root *UsersOnAccessGroupsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uoags.fns))
	for _, fn := range uoags.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uoags.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uoags.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
