// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"shared/infrastructure/persistence/postgres/ent/userstatus"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserStatus is the model entity for the UserStatus schema.
type UserStatus struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ExternalID holds the value of the "external_id" field.
	ExternalID string `json:"external_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserStatusQuery when eager-loading is set.
	Edges        UserStatusEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserStatusEdges holds the relations/edges for other nodes in the graph.
type UserStatusEdges struct {
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e UserStatusEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserStatus) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userstatus.FieldID:
			values[i] = new(sql.NullInt64)
		case userstatus.FieldExternalID, userstatus.FieldName:
			values[i] = new(sql.NullString)
		case userstatus.FieldCreatedAt, userstatus.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserStatus fields.
func (us *UserStatus) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userstatus.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			us.ID = int(value.Int64)
		case userstatus.FieldExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				us.ExternalID = value.String
			}
		case userstatus.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				us.Name = value.String
			}
		case userstatus.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				us.CreatedAt = value.Time
			}
		case userstatus.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				us.UpdatedAt = value.Time
			}
		default:
			us.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserStatus.
// This includes values selected through modifiers, order, etc.
func (us *UserStatus) Value(name string) (ent.Value, error) {
	return us.selectValues.Get(name)
}

// QueryUsers queries the "users" edge of the UserStatus entity.
func (us *UserStatus) QueryUsers() *UserQuery {
	return NewUserStatusClient(us.config).QueryUsers(us)
}

// Update returns a builder for updating this UserStatus.
// Note that you need to call UserStatus.Unwrap() before calling this method if this UserStatus
// was returned from a transaction, and the transaction was committed or rolled back.
func (us *UserStatus) Update() *UserStatusUpdateOne {
	return NewUserStatusClient(us.config).UpdateOne(us)
}

// Unwrap unwraps the UserStatus entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (us *UserStatus) Unwrap() *UserStatus {
	_tx, ok := us.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserStatus is not a transactional entity")
	}
	us.config.driver = _tx.drv
	return us
}

// String implements the fmt.Stringer.
func (us *UserStatus) String() string {
	var builder strings.Builder
	builder.WriteString("UserStatus(")
	builder.WriteString(fmt.Sprintf("id=%v, ", us.ID))
	builder.WriteString("external_id=")
	builder.WriteString(us.ExternalID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(us.Name)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(us.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(us.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserStatusSlice is a parsable slice of UserStatus.
type UserStatusSlice []*UserStatus
