// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shared/infrastructure/persistence/postgres/ent/accessgroup"
	"shared/infrastructure/persistence/postgres/ent/predicate"
	"shared/infrastructure/persistence/postgres/ent/user"
	"shared/infrastructure/persistence/postgres/ent/usersonaccessgroups"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UsersOnAccessGroupsUpdate is the builder for updating UsersOnAccessGroups entities.
type UsersOnAccessGroupsUpdate struct {
	config
	hooks    []Hook
	mutation *UsersOnAccessGroupsMutation
}

// Where appends a list predicates to the UsersOnAccessGroupsUpdate builder.
func (uoagu *UsersOnAccessGroupsUpdate) Where(ps ...predicate.UsersOnAccessGroups) *UsersOnAccessGroupsUpdate {
	uoagu.mutation.Where(ps...)
	return uoagu
}

// SetUserID sets the "user_id" field.
func (uoagu *UsersOnAccessGroupsUpdate) SetUserID(u uuid.UUID) *UsersOnAccessGroupsUpdate {
	uoagu.mutation.SetUserID(u)
	return uoagu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (uoagu *UsersOnAccessGroupsUpdate) SetNillableUserID(u *uuid.UUID) *UsersOnAccessGroupsUpdate {
	if u != nil {
		uoagu.SetUserID(*u)
	}
	return uoagu
}

// SetAccessGroupID sets the "access_group_id" field.
func (uoagu *UsersOnAccessGroupsUpdate) SetAccessGroupID(i int) *UsersOnAccessGroupsUpdate {
	uoagu.mutation.SetAccessGroupID(i)
	return uoagu
}

// SetNillableAccessGroupID sets the "access_group_id" field if the given value is not nil.
func (uoagu *UsersOnAccessGroupsUpdate) SetNillableAccessGroupID(i *int) *UsersOnAccessGroupsUpdate {
	if i != nil {
		uoagu.SetAccessGroupID(*i)
	}
	return uoagu
}

// SetCreatedAt sets the "created_at" field.
func (uoagu *UsersOnAccessGroupsUpdate) SetCreatedAt(t time.Time) *UsersOnAccessGroupsUpdate {
	uoagu.mutation.SetCreatedAt(t)
	return uoagu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uoagu *UsersOnAccessGroupsUpdate) SetNillableCreatedAt(t *time.Time) *UsersOnAccessGroupsUpdate {
	if t != nil {
		uoagu.SetCreatedAt(*t)
	}
	return uoagu
}

// SetUpdatedAt sets the "updated_at" field.
func (uoagu *UsersOnAccessGroupsUpdate) SetUpdatedAt(t time.Time) *UsersOnAccessGroupsUpdate {
	uoagu.mutation.SetUpdatedAt(t)
	return uoagu
}

// SetUser sets the "user" edge to the User entity.
func (uoagu *UsersOnAccessGroupsUpdate) SetUser(u *User) *UsersOnAccessGroupsUpdate {
	return uoagu.SetUserID(u.ID)
}

// SetAccessGroup sets the "access_group" edge to the AccessGroup entity.
func (uoagu *UsersOnAccessGroupsUpdate) SetAccessGroup(a *AccessGroup) *UsersOnAccessGroupsUpdate {
	return uoagu.SetAccessGroupID(a.ID)
}

// Mutation returns the UsersOnAccessGroupsMutation object of the builder.
func (uoagu *UsersOnAccessGroupsUpdate) Mutation() *UsersOnAccessGroupsMutation {
	return uoagu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (uoagu *UsersOnAccessGroupsUpdate) ClearUser() *UsersOnAccessGroupsUpdate {
	uoagu.mutation.ClearUser()
	return uoagu
}

// ClearAccessGroup clears the "access_group" edge to the AccessGroup entity.
func (uoagu *UsersOnAccessGroupsUpdate) ClearAccessGroup() *UsersOnAccessGroupsUpdate {
	uoagu.mutation.ClearAccessGroup()
	return uoagu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uoagu *UsersOnAccessGroupsUpdate) Save(ctx context.Context) (int, error) {
	uoagu.defaults()
	return withHooks(ctx, uoagu.sqlSave, uoagu.mutation, uoagu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uoagu *UsersOnAccessGroupsUpdate) SaveX(ctx context.Context) int {
	affected, err := uoagu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uoagu *UsersOnAccessGroupsUpdate) Exec(ctx context.Context) error {
	_, err := uoagu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uoagu *UsersOnAccessGroupsUpdate) ExecX(ctx context.Context) {
	if err := uoagu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uoagu *UsersOnAccessGroupsUpdate) defaults() {
	if _, ok := uoagu.mutation.UpdatedAt(); !ok {
		v := usersonaccessgroups.UpdateDefaultUpdatedAt()
		uoagu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uoagu *UsersOnAccessGroupsUpdate) check() error {
	if _, ok := uoagu.mutation.UserID(); uoagu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UsersOnAccessGroups.user"`)
	}
	if _, ok := uoagu.mutation.AccessGroupID(); uoagu.mutation.AccessGroupCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UsersOnAccessGroups.access_group"`)
	}
	return nil
}

func (uoagu *UsersOnAccessGroupsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uoagu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersonaccessgroups.Table, usersonaccessgroups.Columns, sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt))
	if ps := uoagu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uoagu.mutation.CreatedAt(); ok {
		_spec.SetField(usersonaccessgroups.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := uoagu.mutation.UpdatedAt(); ok {
		_spec.SetField(usersonaccessgroups.FieldUpdatedAt, field.TypeTime, value)
	}
	if uoagu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersonaccessgroups.UserTable,
			Columns: []string{usersonaccessgroups.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uoagu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersonaccessgroups.UserTable,
			Columns: []string{usersonaccessgroups.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uoagu.mutation.AccessGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersonaccessgroups.AccessGroupTable,
			Columns: []string{usersonaccessgroups.AccessGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accessgroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uoagu.mutation.AccessGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersonaccessgroups.AccessGroupTable,
			Columns: []string{usersonaccessgroups.AccessGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accessgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uoagu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersonaccessgroups.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uoagu.mutation.done = true
	return n, nil
}

// UsersOnAccessGroupsUpdateOne is the builder for updating a single UsersOnAccessGroups entity.
type UsersOnAccessGroupsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsersOnAccessGroupsMutation
}

// SetUserID sets the "user_id" field.
func (uoaguo *UsersOnAccessGroupsUpdateOne) SetUserID(u uuid.UUID) *UsersOnAccessGroupsUpdateOne {
	uoaguo.mutation.SetUserID(u)
	return uoaguo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (uoaguo *UsersOnAccessGroupsUpdateOne) SetNillableUserID(u *uuid.UUID) *UsersOnAccessGroupsUpdateOne {
	if u != nil {
		uoaguo.SetUserID(*u)
	}
	return uoaguo
}

// SetAccessGroupID sets the "access_group_id" field.
func (uoaguo *UsersOnAccessGroupsUpdateOne) SetAccessGroupID(i int) *UsersOnAccessGroupsUpdateOne {
	uoaguo.mutation.SetAccessGroupID(i)
	return uoaguo
}

// SetNillableAccessGroupID sets the "access_group_id" field if the given value is not nil.
func (uoaguo *UsersOnAccessGroupsUpdateOne) SetNillableAccessGroupID(i *int) *UsersOnAccessGroupsUpdateOne {
	if i != nil {
		uoaguo.SetAccessGroupID(*i)
	}
	return uoaguo
}

// SetCreatedAt sets the "created_at" field.
func (uoaguo *UsersOnAccessGroupsUpdateOne) SetCreatedAt(t time.Time) *UsersOnAccessGroupsUpdateOne {
	uoaguo.mutation.SetCreatedAt(t)
	return uoaguo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uoaguo *UsersOnAccessGroupsUpdateOne) SetNillableCreatedAt(t *time.Time) *UsersOnAccessGroupsUpdateOne {
	if t != nil {
		uoaguo.SetCreatedAt(*t)
	}
	return uoaguo
}

// SetUpdatedAt sets the "updated_at" field.
func (uoaguo *UsersOnAccessGroupsUpdateOne) SetUpdatedAt(t time.Time) *UsersOnAccessGroupsUpdateOne {
	uoaguo.mutation.SetUpdatedAt(t)
	return uoaguo
}

// SetUser sets the "user" edge to the User entity.
func (uoaguo *UsersOnAccessGroupsUpdateOne) SetUser(u *User) *UsersOnAccessGroupsUpdateOne {
	return uoaguo.SetUserID(u.ID)
}

// SetAccessGroup sets the "access_group" edge to the AccessGroup entity.
func (uoaguo *UsersOnAccessGroupsUpdateOne) SetAccessGroup(a *AccessGroup) *UsersOnAccessGroupsUpdateOne {
	return uoaguo.SetAccessGroupID(a.ID)
}

// Mutation returns the UsersOnAccessGroupsMutation object of the builder.
func (uoaguo *UsersOnAccessGroupsUpdateOne) Mutation() *UsersOnAccessGroupsMutation {
	return uoaguo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (uoaguo *UsersOnAccessGroupsUpdateOne) ClearUser() *UsersOnAccessGroupsUpdateOne {
	uoaguo.mutation.ClearUser()
	return uoaguo
}

// ClearAccessGroup clears the "access_group" edge to the AccessGroup entity.
func (uoaguo *UsersOnAccessGroupsUpdateOne) ClearAccessGroup() *UsersOnAccessGroupsUpdateOne {
	uoaguo.mutation.ClearAccessGroup()
	return uoaguo
}

// Where appends a list predicates to the UsersOnAccessGroupsUpdate builder.
func (uoaguo *UsersOnAccessGroupsUpdateOne) Where(ps ...predicate.UsersOnAccessGroups) *UsersOnAccessGroupsUpdateOne {
	uoaguo.mutation.Where(ps...)
	return uoaguo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uoaguo *UsersOnAccessGroupsUpdateOne) Select(field string, fields ...string) *UsersOnAccessGroupsUpdateOne {
	uoaguo.fields = append([]string{field}, fields...)
	return uoaguo
}

// Save executes the query and returns the updated UsersOnAccessGroups entity.
func (uoaguo *UsersOnAccessGroupsUpdateOne) Save(ctx context.Context) (*UsersOnAccessGroups, error) {
	uoaguo.defaults()
	return withHooks(ctx, uoaguo.sqlSave, uoaguo.mutation, uoaguo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uoaguo *UsersOnAccessGroupsUpdateOne) SaveX(ctx context.Context) *UsersOnAccessGroups {
	node, err := uoaguo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uoaguo *UsersOnAccessGroupsUpdateOne) Exec(ctx context.Context) error {
	_, err := uoaguo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uoaguo *UsersOnAccessGroupsUpdateOne) ExecX(ctx context.Context) {
	if err := uoaguo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uoaguo *UsersOnAccessGroupsUpdateOne) defaults() {
	if _, ok := uoaguo.mutation.UpdatedAt(); !ok {
		v := usersonaccessgroups.UpdateDefaultUpdatedAt()
		uoaguo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uoaguo *UsersOnAccessGroupsUpdateOne) check() error {
	if _, ok := uoaguo.mutation.UserID(); uoaguo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UsersOnAccessGroups.user"`)
	}
	if _, ok := uoaguo.mutation.AccessGroupID(); uoaguo.mutation.AccessGroupCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UsersOnAccessGroups.access_group"`)
	}
	return nil
}

func (uoaguo *UsersOnAccessGroupsUpdateOne) sqlSave(ctx context.Context) (_node *UsersOnAccessGroups, err error) {
	if err := uoaguo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersonaccessgroups.Table, usersonaccessgroups.Columns, sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt))
	id, ok := uoaguo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsersOnAccessGroups.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uoaguo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersonaccessgroups.FieldID)
		for _, f := range fields {
			if !usersonaccessgroups.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usersonaccessgroups.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uoaguo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uoaguo.mutation.CreatedAt(); ok {
		_spec.SetField(usersonaccessgroups.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := uoaguo.mutation.UpdatedAt(); ok {
		_spec.SetField(usersonaccessgroups.FieldUpdatedAt, field.TypeTime, value)
	}
	if uoaguo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersonaccessgroups.UserTable,
			Columns: []string{usersonaccessgroups.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uoaguo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersonaccessgroups.UserTable,
			Columns: []string{usersonaccessgroups.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uoaguo.mutation.AccessGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersonaccessgroups.AccessGroupTable,
			Columns: []string{usersonaccessgroups.AccessGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accessgroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uoaguo.mutation.AccessGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersonaccessgroups.AccessGroupTable,
			Columns: []string{usersonaccessgroups.AccessGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accessgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UsersOnAccessGroups{config: uoaguo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uoaguo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersonaccessgroups.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uoaguo.mutation.done = true
	return _node, nil
}
