// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shared/infrastructure/persistence/postgres/ent/business"
	"shared/infrastructure/persistence/postgres/ent/predicate"
	"shared/infrastructure/persistence/postgres/ent/user"
	"shared/infrastructure/persistence/postgres/ent/usersonaccessgroups"
	"shared/infrastructure/persistence/postgres/ent/userstatus"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetName sets the "name" field.
func (uu *UserUpdate) SetName(s string) *UserUpdate {
	uu.mutation.SetName(s)
	return uu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uu *UserUpdate) SetNillableName(s *string) *UserUpdate {
	if s != nil {
		uu.SetName(*s)
	}
	return uu
}

// ClearName clears the value of the "name" field.
func (uu *UserUpdate) ClearName() *UserUpdate {
	uu.mutation.ClearName()
	return uu
}

// SetPassword sets the "password" field.
func (uu *UserUpdate) SetPassword(s string) *UserUpdate {
	uu.mutation.SetPassword(s)
	return uu
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (uu *UserUpdate) SetNillablePassword(s *string) *UserUpdate {
	if s != nil {
		uu.SetPassword(*s)
	}
	return uu
}

// SetIsManager sets the "is_manager" field.
func (uu *UserUpdate) SetIsManager(b bool) *UserUpdate {
	uu.mutation.SetIsManager(b)
	return uu
}

// SetNillableIsManager sets the "is_manager" field if the given value is not nil.
func (uu *UserUpdate) SetNillableIsManager(b *bool) *UserUpdate {
	if b != nil {
		uu.SetIsManager(*b)
	}
	return uu
}

// SetPhotoURL sets the "photo_url" field.
func (uu *UserUpdate) SetPhotoURL(s string) *UserUpdate {
	uu.mutation.SetPhotoURL(s)
	return uu
}

// SetNillablePhotoURL sets the "photo_url" field if the given value is not nil.
func (uu *UserUpdate) SetNillablePhotoURL(s *string) *UserUpdate {
	if s != nil {
		uu.SetPhotoURL(*s)
	}
	return uu
}

// ClearPhotoURL clears the value of the "photo_url" field.
func (uu *UserUpdate) ClearPhotoURL() *UserUpdate {
	uu.mutation.ClearPhotoURL()
	return uu
}

// SetDocument sets the "document" field.
func (uu *UserUpdate) SetDocument(s string) *UserUpdate {
	uu.mutation.SetDocument(s)
	return uu
}

// SetNillableDocument sets the "document" field if the given value is not nil.
func (uu *UserUpdate) SetNillableDocument(s *string) *UserUpdate {
	if s != nil {
		uu.SetDocument(*s)
	}
	return uu
}

// SetEmail sets the "email" field.
func (uu *UserUpdate) SetEmail(s string) *UserUpdate {
	uu.mutation.SetEmail(s)
	return uu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (uu *UserUpdate) SetNillableEmail(s *string) *UserUpdate {
	if s != nil {
		uu.SetEmail(*s)
	}
	return uu
}

// ClearEmail clears the value of the "email" field.
func (uu *UserUpdate) ClearEmail() *UserUpdate {
	uu.mutation.ClearEmail()
	return uu
}

// SetManagerID sets the "manager_id" field.
func (uu *UserUpdate) SetManagerID(u uuid.UUID) *UserUpdate {
	uu.mutation.SetManagerID(u)
	return uu
}

// SetNillableManagerID sets the "manager_id" field if the given value is not nil.
func (uu *UserUpdate) SetNillableManagerID(u *uuid.UUID) *UserUpdate {
	if u != nil {
		uu.SetManagerID(*u)
	}
	return uu
}

// ClearManagerID clears the value of the "manager_id" field.
func (uu *UserUpdate) ClearManagerID() *UserUpdate {
	uu.mutation.ClearManagerID()
	return uu
}

// SetUserStatusID sets the "user_status_id" field.
func (uu *UserUpdate) SetUserStatusID(i int) *UserUpdate {
	uu.mutation.SetUserStatusID(i)
	return uu
}

// SetNillableUserStatusID sets the "user_status_id" field if the given value is not nil.
func (uu *UserUpdate) SetNillableUserStatusID(i *int) *UserUpdate {
	if i != nil {
		uu.SetUserStatusID(*i)
	}
	return uu
}

// ClearUserStatusID clears the value of the "user_status_id" field.
func (uu *UserUpdate) ClearUserStatusID() *UserUpdate {
	uu.mutation.ClearUserStatusID()
	return uu
}

// SetDeactivatedAt sets the "deactivated_at" field.
func (uu *UserUpdate) SetDeactivatedAt(t time.Time) *UserUpdate {
	uu.mutation.SetDeactivatedAt(t)
	return uu
}

// SetNillableDeactivatedAt sets the "deactivated_at" field if the given value is not nil.
func (uu *UserUpdate) SetNillableDeactivatedAt(t *time.Time) *UserUpdate {
	if t != nil {
		uu.SetDeactivatedAt(*t)
	}
	return uu
}

// ClearDeactivatedAt clears the value of the "deactivated_at" field.
func (uu *UserUpdate) ClearDeactivatedAt() *UserUpdate {
	uu.mutation.ClearDeactivatedAt()
	return uu
}

// SetCreatedAt sets the "created_at" field.
func (uu *UserUpdate) SetCreatedAt(t time.Time) *UserUpdate {
	uu.mutation.SetCreatedAt(t)
	return uu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uu *UserUpdate) SetNillableCreatedAt(t *time.Time) *UserUpdate {
	if t != nil {
		uu.SetCreatedAt(*t)
	}
	return uu
}

// SetUpdatedAt sets the "updated_at" field.
func (uu *UserUpdate) SetUpdatedAt(t time.Time) *UserUpdate {
	uu.mutation.SetUpdatedAt(t)
	return uu
}

// SetManager sets the "manager" edge to the User entity.
func (uu *UserUpdate) SetManager(u *User) *UserUpdate {
	return uu.SetManagerID(u.ID)
}

// AddSubordinateIDs adds the "subordinates" edge to the User entity by IDs.
func (uu *UserUpdate) AddSubordinateIDs(ids ...uuid.UUID) *UserUpdate {
	uu.mutation.AddSubordinateIDs(ids...)
	return uu
}

// AddSubordinates adds the "subordinates" edges to the User entity.
func (uu *UserUpdate) AddSubordinates(u ...*User) *UserUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uu.AddSubordinateIDs(ids...)
}

// SetBusinessID sets the "business" edge to the Business entity by ID.
func (uu *UserUpdate) SetBusinessID(id int) *UserUpdate {
	uu.mutation.SetBusinessID(id)
	return uu
}

// SetNillableBusinessID sets the "business" edge to the Business entity by ID if the given value is not nil.
func (uu *UserUpdate) SetNillableBusinessID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetBusinessID(*id)
	}
	return uu
}

// SetBusiness sets the "business" edge to the Business entity.
func (uu *UserUpdate) SetBusiness(b *Business) *UserUpdate {
	return uu.SetBusinessID(b.ID)
}

// SetStatusID sets the "status" edge to the UserStatus entity by ID.
func (uu *UserUpdate) SetStatusID(id int) *UserUpdate {
	uu.mutation.SetStatusID(id)
	return uu
}

// SetNillableStatusID sets the "status" edge to the UserStatus entity by ID if the given value is not nil.
func (uu *UserUpdate) SetNillableStatusID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetStatusID(*id)
	}
	return uu
}

// SetStatus sets the "status" edge to the UserStatus entity.
func (uu *UserUpdate) SetStatus(u *UserStatus) *UserUpdate {
	return uu.SetStatusID(u.ID)
}

// AddAccessGroupIDs adds the "access_groups" edge to the UsersOnAccessGroups entity by IDs.
func (uu *UserUpdate) AddAccessGroupIDs(ids ...int) *UserUpdate {
	uu.mutation.AddAccessGroupIDs(ids...)
	return uu
}

// AddAccessGroups adds the "access_groups" edges to the UsersOnAccessGroups entity.
func (uu *UserUpdate) AddAccessGroups(u ...*UsersOnAccessGroups) *UserUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uu.AddAccessGroupIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// ClearManager clears the "manager" edge to the User entity.
func (uu *UserUpdate) ClearManager() *UserUpdate {
	uu.mutation.ClearManager()
	return uu
}

// ClearSubordinates clears all "subordinates" edges to the User entity.
func (uu *UserUpdate) ClearSubordinates() *UserUpdate {
	uu.mutation.ClearSubordinates()
	return uu
}

// RemoveSubordinateIDs removes the "subordinates" edge to User entities by IDs.
func (uu *UserUpdate) RemoveSubordinateIDs(ids ...uuid.UUID) *UserUpdate {
	uu.mutation.RemoveSubordinateIDs(ids...)
	return uu
}

// RemoveSubordinates removes "subordinates" edges to User entities.
func (uu *UserUpdate) RemoveSubordinates(u ...*User) *UserUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uu.RemoveSubordinateIDs(ids...)
}

// ClearBusiness clears the "business" edge to the Business entity.
func (uu *UserUpdate) ClearBusiness() *UserUpdate {
	uu.mutation.ClearBusiness()
	return uu
}

// ClearStatus clears the "status" edge to the UserStatus entity.
func (uu *UserUpdate) ClearStatus() *UserUpdate {
	uu.mutation.ClearStatus()
	return uu
}

// ClearAccessGroups clears all "access_groups" edges to the UsersOnAccessGroups entity.
func (uu *UserUpdate) ClearAccessGroups() *UserUpdate {
	uu.mutation.ClearAccessGroups()
	return uu
}

// RemoveAccessGroupIDs removes the "access_groups" edge to UsersOnAccessGroups entities by IDs.
func (uu *UserUpdate) RemoveAccessGroupIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveAccessGroupIDs(ids...)
	return uu
}

// RemoveAccessGroups removes "access_groups" edges to UsersOnAccessGroups entities.
func (uu *UserUpdate) RemoveAccessGroups(u ...*UsersOnAccessGroups) *UserUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uu.RemoveAccessGroupIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	uu.defaults()
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uu *UserUpdate) defaults() {
	if _, ok := uu.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		uu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uu *UserUpdate) check() error {
	if v, ok := uu.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if v, ok := uu.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "User.password": %w`, err)}
		}
	}
	if v, ok := uu.mutation.PhotoURL(); ok {
		if err := user.PhotoURLValidator(v); err != nil {
			return &ValidationError{Name: "photo_url", err: fmt.Errorf(`ent: validator failed for field "User.photo_url": %w`, err)}
		}
	}
	if v, ok := uu.mutation.Document(); ok {
		if err := user.DocumentValidator(v); err != nil {
			return &ValidationError{Name: "document", err: fmt.Errorf(`ent: validator failed for field "User.document": %w`, err)}
		}
	}
	if v, ok := uu.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	return nil
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if uu.mutation.NameCleared() {
		_spec.ClearField(user.FieldName, field.TypeString)
	}
	if value, ok := uu.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := uu.mutation.IsManager(); ok {
		_spec.SetField(user.FieldIsManager, field.TypeBool, value)
	}
	if value, ok := uu.mutation.PhotoURL(); ok {
		_spec.SetField(user.FieldPhotoURL, field.TypeString, value)
	}
	if uu.mutation.PhotoURLCleared() {
		_spec.ClearField(user.FieldPhotoURL, field.TypeString)
	}
	if value, ok := uu.mutation.Document(); ok {
		_spec.SetField(user.FieldDocument, field.TypeString, value)
	}
	if value, ok := uu.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if uu.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := uu.mutation.DeactivatedAt(); ok {
		_spec.SetField(user.FieldDeactivatedAt, field.TypeTime, value)
	}
	if uu.mutation.DeactivatedAtCleared() {
		_spec.ClearField(user.FieldDeactivatedAt, field.TypeTime)
	}
	if value, ok := uu.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := uu.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if uu.mutation.ManagerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.ManagerTable,
			Columns: []string{user.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.ManagerTable,
			Columns: []string{user.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.SubordinatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SubordinatesTable,
			Columns: []string{user.SubordinatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedSubordinatesIDs(); len(nodes) > 0 && !uu.mutation.SubordinatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SubordinatesTable,
			Columns: []string{user.SubordinatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.SubordinatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SubordinatesTable,
			Columns: []string{user.SubordinatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.BusinessCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   user.BusinessTable,
			Columns: []string{user.BusinessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(business.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.BusinessIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   user.BusinessTable,
			Columns: []string{user.BusinessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(business.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.StatusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.StatusTable,
			Columns: []string{user.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userstatus.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.StatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.StatusTable,
			Columns: []string{user.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userstatus.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.AccessGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AccessGroupsTable,
			Columns: []string{user.AccessGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedAccessGroupsIDs(); len(nodes) > 0 && !uu.mutation.AccessGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AccessGroupsTable,
			Columns: []string{user.AccessGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.AccessGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AccessGroupsTable,
			Columns: []string{user.AccessGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetName sets the "name" field.
func (uuo *UserUpdateOne) SetName(s string) *UserUpdateOne {
	uuo.mutation.SetName(s)
	return uuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableName(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetName(*s)
	}
	return uuo
}

// ClearName clears the value of the "name" field.
func (uuo *UserUpdateOne) ClearName() *UserUpdateOne {
	uuo.mutation.ClearName()
	return uuo
}

// SetPassword sets the "password" field.
func (uuo *UserUpdateOne) SetPassword(s string) *UserUpdateOne {
	uuo.mutation.SetPassword(s)
	return uuo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillablePassword(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetPassword(*s)
	}
	return uuo
}

// SetIsManager sets the "is_manager" field.
func (uuo *UserUpdateOne) SetIsManager(b bool) *UserUpdateOne {
	uuo.mutation.SetIsManager(b)
	return uuo
}

// SetNillableIsManager sets the "is_manager" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableIsManager(b *bool) *UserUpdateOne {
	if b != nil {
		uuo.SetIsManager(*b)
	}
	return uuo
}

// SetPhotoURL sets the "photo_url" field.
func (uuo *UserUpdateOne) SetPhotoURL(s string) *UserUpdateOne {
	uuo.mutation.SetPhotoURL(s)
	return uuo
}

// SetNillablePhotoURL sets the "photo_url" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillablePhotoURL(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetPhotoURL(*s)
	}
	return uuo
}

// ClearPhotoURL clears the value of the "photo_url" field.
func (uuo *UserUpdateOne) ClearPhotoURL() *UserUpdateOne {
	uuo.mutation.ClearPhotoURL()
	return uuo
}

// SetDocument sets the "document" field.
func (uuo *UserUpdateOne) SetDocument(s string) *UserUpdateOne {
	uuo.mutation.SetDocument(s)
	return uuo
}

// SetNillableDocument sets the "document" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableDocument(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetDocument(*s)
	}
	return uuo
}

// SetEmail sets the "email" field.
func (uuo *UserUpdateOne) SetEmail(s string) *UserUpdateOne {
	uuo.mutation.SetEmail(s)
	return uuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableEmail(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetEmail(*s)
	}
	return uuo
}

// ClearEmail clears the value of the "email" field.
func (uuo *UserUpdateOne) ClearEmail() *UserUpdateOne {
	uuo.mutation.ClearEmail()
	return uuo
}

// SetManagerID sets the "manager_id" field.
func (uuo *UserUpdateOne) SetManagerID(u uuid.UUID) *UserUpdateOne {
	uuo.mutation.SetManagerID(u)
	return uuo
}

// SetNillableManagerID sets the "manager_id" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableManagerID(u *uuid.UUID) *UserUpdateOne {
	if u != nil {
		uuo.SetManagerID(*u)
	}
	return uuo
}

// ClearManagerID clears the value of the "manager_id" field.
func (uuo *UserUpdateOne) ClearManagerID() *UserUpdateOne {
	uuo.mutation.ClearManagerID()
	return uuo
}

// SetUserStatusID sets the "user_status_id" field.
func (uuo *UserUpdateOne) SetUserStatusID(i int) *UserUpdateOne {
	uuo.mutation.SetUserStatusID(i)
	return uuo
}

// SetNillableUserStatusID sets the "user_status_id" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableUserStatusID(i *int) *UserUpdateOne {
	if i != nil {
		uuo.SetUserStatusID(*i)
	}
	return uuo
}

// ClearUserStatusID clears the value of the "user_status_id" field.
func (uuo *UserUpdateOne) ClearUserStatusID() *UserUpdateOne {
	uuo.mutation.ClearUserStatusID()
	return uuo
}

// SetDeactivatedAt sets the "deactivated_at" field.
func (uuo *UserUpdateOne) SetDeactivatedAt(t time.Time) *UserUpdateOne {
	uuo.mutation.SetDeactivatedAt(t)
	return uuo
}

// SetNillableDeactivatedAt sets the "deactivated_at" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableDeactivatedAt(t *time.Time) *UserUpdateOne {
	if t != nil {
		uuo.SetDeactivatedAt(*t)
	}
	return uuo
}

// ClearDeactivatedAt clears the value of the "deactivated_at" field.
func (uuo *UserUpdateOne) ClearDeactivatedAt() *UserUpdateOne {
	uuo.mutation.ClearDeactivatedAt()
	return uuo
}

// SetCreatedAt sets the "created_at" field.
func (uuo *UserUpdateOne) SetCreatedAt(t time.Time) *UserUpdateOne {
	uuo.mutation.SetCreatedAt(t)
	return uuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableCreatedAt(t *time.Time) *UserUpdateOne {
	if t != nil {
		uuo.SetCreatedAt(*t)
	}
	return uuo
}

// SetUpdatedAt sets the "updated_at" field.
func (uuo *UserUpdateOne) SetUpdatedAt(t time.Time) *UserUpdateOne {
	uuo.mutation.SetUpdatedAt(t)
	return uuo
}

// SetManager sets the "manager" edge to the User entity.
func (uuo *UserUpdateOne) SetManager(u *User) *UserUpdateOne {
	return uuo.SetManagerID(u.ID)
}

// AddSubordinateIDs adds the "subordinates" edge to the User entity by IDs.
func (uuo *UserUpdateOne) AddSubordinateIDs(ids ...uuid.UUID) *UserUpdateOne {
	uuo.mutation.AddSubordinateIDs(ids...)
	return uuo
}

// AddSubordinates adds the "subordinates" edges to the User entity.
func (uuo *UserUpdateOne) AddSubordinates(u ...*User) *UserUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uuo.AddSubordinateIDs(ids...)
}

// SetBusinessID sets the "business" edge to the Business entity by ID.
func (uuo *UserUpdateOne) SetBusinessID(id int) *UserUpdateOne {
	uuo.mutation.SetBusinessID(id)
	return uuo
}

// SetNillableBusinessID sets the "business" edge to the Business entity by ID if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableBusinessID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetBusinessID(*id)
	}
	return uuo
}

// SetBusiness sets the "business" edge to the Business entity.
func (uuo *UserUpdateOne) SetBusiness(b *Business) *UserUpdateOne {
	return uuo.SetBusinessID(b.ID)
}

// SetStatusID sets the "status" edge to the UserStatus entity by ID.
func (uuo *UserUpdateOne) SetStatusID(id int) *UserUpdateOne {
	uuo.mutation.SetStatusID(id)
	return uuo
}

// SetNillableStatusID sets the "status" edge to the UserStatus entity by ID if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableStatusID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetStatusID(*id)
	}
	return uuo
}

// SetStatus sets the "status" edge to the UserStatus entity.
func (uuo *UserUpdateOne) SetStatus(u *UserStatus) *UserUpdateOne {
	return uuo.SetStatusID(u.ID)
}

// AddAccessGroupIDs adds the "access_groups" edge to the UsersOnAccessGroups entity by IDs.
func (uuo *UserUpdateOne) AddAccessGroupIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddAccessGroupIDs(ids...)
	return uuo
}

// AddAccessGroups adds the "access_groups" edges to the UsersOnAccessGroups entity.
func (uuo *UserUpdateOne) AddAccessGroups(u ...*UsersOnAccessGroups) *UserUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uuo.AddAccessGroupIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// ClearManager clears the "manager" edge to the User entity.
func (uuo *UserUpdateOne) ClearManager() *UserUpdateOne {
	uuo.mutation.ClearManager()
	return uuo
}

// ClearSubordinates clears all "subordinates" edges to the User entity.
func (uuo *UserUpdateOne) ClearSubordinates() *UserUpdateOne {
	uuo.mutation.ClearSubordinates()
	return uuo
}

// RemoveSubordinateIDs removes the "subordinates" edge to User entities by IDs.
func (uuo *UserUpdateOne) RemoveSubordinateIDs(ids ...uuid.UUID) *UserUpdateOne {
	uuo.mutation.RemoveSubordinateIDs(ids...)
	return uuo
}

// RemoveSubordinates removes "subordinates" edges to User entities.
func (uuo *UserUpdateOne) RemoveSubordinates(u ...*User) *UserUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uuo.RemoveSubordinateIDs(ids...)
}

// ClearBusiness clears the "business" edge to the Business entity.
func (uuo *UserUpdateOne) ClearBusiness() *UserUpdateOne {
	uuo.mutation.ClearBusiness()
	return uuo
}

// ClearStatus clears the "status" edge to the UserStatus entity.
func (uuo *UserUpdateOne) ClearStatus() *UserUpdateOne {
	uuo.mutation.ClearStatus()
	return uuo
}

// ClearAccessGroups clears all "access_groups" edges to the UsersOnAccessGroups entity.
func (uuo *UserUpdateOne) ClearAccessGroups() *UserUpdateOne {
	uuo.mutation.ClearAccessGroups()
	return uuo
}

// RemoveAccessGroupIDs removes the "access_groups" edge to UsersOnAccessGroups entities by IDs.
func (uuo *UserUpdateOne) RemoveAccessGroupIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveAccessGroupIDs(ids...)
	return uuo
}

// RemoveAccessGroups removes "access_groups" edges to UsersOnAccessGroups entities.
func (uuo *UserUpdateOne) RemoveAccessGroups(u ...*UsersOnAccessGroups) *UserUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uuo.RemoveAccessGroupIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (uuo *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	uuo.defaults()
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uuo *UserUpdateOne) defaults() {
	if _, ok := uuo.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		uuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uuo *UserUpdateOne) check() error {
	if v, ok := uuo.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "User.password": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.PhotoURL(); ok {
		if err := user.PhotoURLValidator(v); err != nil {
			return &ValidationError{Name: "photo_url", err: fmt.Errorf(`ent: validator failed for field "User.photo_url": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.Document(); ok {
		if err := user.DocumentValidator(v); err != nil {
			return &ValidationError{Name: "document", err: fmt.Errorf(`ent: validator failed for field "User.document": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	return nil
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := uuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if uuo.mutation.NameCleared() {
		_spec.ClearField(user.FieldName, field.TypeString)
	}
	if value, ok := uuo.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := uuo.mutation.IsManager(); ok {
		_spec.SetField(user.FieldIsManager, field.TypeBool, value)
	}
	if value, ok := uuo.mutation.PhotoURL(); ok {
		_spec.SetField(user.FieldPhotoURL, field.TypeString, value)
	}
	if uuo.mutation.PhotoURLCleared() {
		_spec.ClearField(user.FieldPhotoURL, field.TypeString)
	}
	if value, ok := uuo.mutation.Document(); ok {
		_spec.SetField(user.FieldDocument, field.TypeString, value)
	}
	if value, ok := uuo.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if uuo.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := uuo.mutation.DeactivatedAt(); ok {
		_spec.SetField(user.FieldDeactivatedAt, field.TypeTime, value)
	}
	if uuo.mutation.DeactivatedAtCleared() {
		_spec.ClearField(user.FieldDeactivatedAt, field.TypeTime)
	}
	if value, ok := uuo.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := uuo.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if uuo.mutation.ManagerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.ManagerTable,
			Columns: []string{user.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.ManagerTable,
			Columns: []string{user.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.SubordinatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SubordinatesTable,
			Columns: []string{user.SubordinatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedSubordinatesIDs(); len(nodes) > 0 && !uuo.mutation.SubordinatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SubordinatesTable,
			Columns: []string{user.SubordinatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.SubordinatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SubordinatesTable,
			Columns: []string{user.SubordinatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.BusinessCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   user.BusinessTable,
			Columns: []string{user.BusinessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(business.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.BusinessIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   user.BusinessTable,
			Columns: []string{user.BusinessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(business.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.StatusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.StatusTable,
			Columns: []string{user.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userstatus.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.StatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.StatusTable,
			Columns: []string{user.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userstatus.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.AccessGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AccessGroupsTable,
			Columns: []string{user.AccessGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedAccessGroupsIDs(); len(nodes) > 0 && !uuo.mutation.AccessGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AccessGroupsTable,
			Columns: []string{user.AccessGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.AccessGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AccessGroupsTable,
			Columns: []string{user.AccessGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
