// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shared/infrastructure/persistence/postgres/ent/user"
	"shared/infrastructure/persistence/postgres/ent/userstatus"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserStatusCreate is the builder for creating a UserStatus entity.
type UserStatusCreate struct {
	config
	mutation *UserStatusMutation
	hooks    []Hook
}

// SetExternalID sets the "external_id" field.
func (usc *UserStatusCreate) SetExternalID(s string) *UserStatusCreate {
	usc.mutation.SetExternalID(s)
	return usc
}

// SetName sets the "name" field.
func (usc *UserStatusCreate) SetName(s string) *UserStatusCreate {
	usc.mutation.SetName(s)
	return usc
}

// SetCreatedAt sets the "created_at" field.
func (usc *UserStatusCreate) SetCreatedAt(t time.Time) *UserStatusCreate {
	usc.mutation.SetCreatedAt(t)
	return usc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (usc *UserStatusCreate) SetNillableCreatedAt(t *time.Time) *UserStatusCreate {
	if t != nil {
		usc.SetCreatedAt(*t)
	}
	return usc
}

// SetUpdatedAt sets the "updated_at" field.
func (usc *UserStatusCreate) SetUpdatedAt(t time.Time) *UserStatusCreate {
	usc.mutation.SetUpdatedAt(t)
	return usc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (usc *UserStatusCreate) SetNillableUpdatedAt(t *time.Time) *UserStatusCreate {
	if t != nil {
		usc.SetUpdatedAt(*t)
	}
	return usc
}

// SetID sets the "id" field.
func (usc *UserStatusCreate) SetID(i int) *UserStatusCreate {
	usc.mutation.SetID(i)
	return usc
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (usc *UserStatusCreate) AddUserIDs(ids ...uuid.UUID) *UserStatusCreate {
	usc.mutation.AddUserIDs(ids...)
	return usc
}

// AddUsers adds the "users" edges to the User entity.
func (usc *UserStatusCreate) AddUsers(u ...*User) *UserStatusCreate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return usc.AddUserIDs(ids...)
}

// Mutation returns the UserStatusMutation object of the builder.
func (usc *UserStatusCreate) Mutation() *UserStatusMutation {
	return usc.mutation
}

// Save creates the UserStatus in the database.
func (usc *UserStatusCreate) Save(ctx context.Context) (*UserStatus, error) {
	usc.defaults()
	return withHooks(ctx, usc.sqlSave, usc.mutation, usc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (usc *UserStatusCreate) SaveX(ctx context.Context) *UserStatus {
	v, err := usc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (usc *UserStatusCreate) Exec(ctx context.Context) error {
	_, err := usc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usc *UserStatusCreate) ExecX(ctx context.Context) {
	if err := usc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (usc *UserStatusCreate) defaults() {
	if _, ok := usc.mutation.CreatedAt(); !ok {
		v := userstatus.DefaultCreatedAt()
		usc.mutation.SetCreatedAt(v)
	}
	if _, ok := usc.mutation.UpdatedAt(); !ok {
		v := userstatus.DefaultUpdatedAt()
		usc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (usc *UserStatusCreate) check() error {
	if _, ok := usc.mutation.ExternalID(); !ok {
		return &ValidationError{Name: "external_id", err: errors.New(`ent: missing required field "UserStatus.external_id"`)}
	}
	if v, ok := usc.mutation.ExternalID(); ok {
		if err := userstatus.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "UserStatus.external_id": %w`, err)}
		}
	}
	if _, ok := usc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UserStatus.name"`)}
	}
	if v, ok := usc.mutation.Name(); ok {
		if err := userstatus.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserStatus.name": %w`, err)}
		}
	}
	if _, ok := usc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserStatus.created_at"`)}
	}
	if _, ok := usc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserStatus.updated_at"`)}
	}
	if v, ok := usc.mutation.ID(); ok {
		if err := userstatus.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "UserStatus.id": %w`, err)}
		}
	}
	return nil
}

func (usc *UserStatusCreate) sqlSave(ctx context.Context) (*UserStatus, error) {
	if err := usc.check(); err != nil {
		return nil, err
	}
	_node, _spec := usc.createSpec()
	if err := sqlgraph.CreateNode(ctx, usc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	usc.mutation.id = &_node.ID
	usc.mutation.done = true
	return _node, nil
}

func (usc *UserStatusCreate) createSpec() (*UserStatus, *sqlgraph.CreateSpec) {
	var (
		_node = &UserStatus{config: usc.config}
		_spec = sqlgraph.NewCreateSpec(userstatus.Table, sqlgraph.NewFieldSpec(userstatus.FieldID, field.TypeInt))
	)
	if id, ok := usc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := usc.mutation.ExternalID(); ok {
		_spec.SetField(userstatus.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := usc.mutation.Name(); ok {
		_spec.SetField(userstatus.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := usc.mutation.CreatedAt(); ok {
		_spec.SetField(userstatus.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := usc.mutation.UpdatedAt(); ok {
		_spec.SetField(userstatus.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := usc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userstatus.UsersTable,
			Columns: []string{userstatus.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserStatusCreateBulk is the builder for creating many UserStatus entities in bulk.
type UserStatusCreateBulk struct {
	config
	err      error
	builders []*UserStatusCreate
}

// Save creates the UserStatus entities in the database.
func (uscb *UserStatusCreateBulk) Save(ctx context.Context) ([]*UserStatus, error) {
	if uscb.err != nil {
		return nil, uscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uscb.builders))
	nodes := make([]*UserStatus, len(uscb.builders))
	mutators := make([]Mutator, len(uscb.builders))
	for i := range uscb.builders {
		func(i int, root context.Context) {
			builder := uscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserStatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uscb *UserStatusCreateBulk) SaveX(ctx context.Context) []*UserStatus {
	v, err := uscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uscb *UserStatusCreateBulk) Exec(ctx context.Context) error {
	_, err := uscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uscb *UserStatusCreateBulk) ExecX(ctx context.Context) {
	if err := uscb.Exec(ctx); err != nil {
		panic(err)
	}
}
