// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"shared/infrastructure/persistence/postgres/ent/predicate"
	"shared/infrastructure/persistence/postgres/ent/usersonaccessgroups"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UsersOnAccessGroupsDelete is the builder for deleting a UsersOnAccessGroups entity.
type UsersOnAccessGroupsDelete struct {
	config
	hooks    []Hook
	mutation *UsersOnAccessGroupsMutation
}

// Where appends a list predicates to the UsersOnAccessGroupsDelete builder.
func (uoagd *UsersOnAccessGroupsDelete) Where(ps ...predicate.UsersOnAccessGroups) *UsersOnAccessGroupsDelete {
	uoagd.mutation.Where(ps...)
	return uoagd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uoagd *UsersOnAccessGroupsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, uoagd.sqlExec, uoagd.mutation, uoagd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (uoagd *UsersOnAccessGroupsDelete) ExecX(ctx context.Context) int {
	n, err := uoagd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uoagd *UsersOnAccessGroupsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usersonaccessgroups.Table, sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt))
	if ps := uoagd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uoagd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	uoagd.mutation.done = true
	return affected, err
}

// UsersOnAccessGroupsDeleteOne is the builder for deleting a single UsersOnAccessGroups entity.
type UsersOnAccessGroupsDeleteOne struct {
	uoagd *UsersOnAccessGroupsDelete
}

// Where appends a list predicates to the UsersOnAccessGroupsDelete builder.
func (uoagdo *UsersOnAccessGroupsDeleteOne) Where(ps ...predicate.UsersOnAccessGroups) *UsersOnAccessGroupsDeleteOne {
	uoagdo.uoagd.mutation.Where(ps...)
	return uoagdo
}

// Exec executes the deletion query.
func (uoagdo *UsersOnAccessGroupsDeleteOne) Exec(ctx context.Context) error {
	n, err := uoagdo.uoagd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usersonaccessgroups.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uoagdo *UsersOnAccessGroupsDeleteOne) ExecX(ctx context.Context) {
	if err := uoagdo.Exec(ctx); err != nil {
		panic(err)
	}
}
