// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"shared/infrastructure/persistence/postgres/ent/business"
	"shared/infrastructure/persistence/postgres/ent/user"
	"shared/infrastructure/persistence/postgres/ent/userstatus"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"password,omitempty"`
	// IsManager holds the value of the "is_manager" field.
	IsManager bool `json:"is_manager,omitempty"`
	// PhotoURL holds the value of the "photo_url" field.
	PhotoURL string `json:"photo_url,omitempty"`
	// Document holds the value of the "document" field.
	Document string `json:"document,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// ManagerID holds the value of the "manager_id" field.
	ManagerID uuid.UUID `json:"manager_id,omitempty"`
	// UserStatusID holds the value of the "user_status_id" field.
	UserStatusID int `json:"user_status_id,omitempty"`
	// DeactivatedAt holds the value of the "deactivated_at" field.
	DeactivatedAt time.Time `json:"deactivated_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges          UserEdges `json:"edges"`
	business_users *int
	user_business  *int
	selectValues   sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Manager holds the value of the manager edge.
	Manager *User `json:"manager,omitempty"`
	// Subordinates holds the value of the subordinates edge.
	Subordinates []*User `json:"subordinates,omitempty"`
	// Business holds the value of the business edge.
	Business *Business `json:"business,omitempty"`
	// Status holds the value of the status edge.
	Status *UserStatus `json:"status,omitempty"`
	// AccessGroups holds the value of the access_groups edge.
	AccessGroups []*UsersOnAccessGroups `json:"access_groups,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// ManagerOrErr returns the Manager value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) ManagerOrErr() (*User, error) {
	if e.Manager != nil {
		return e.Manager, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "manager"}
}

// SubordinatesOrErr returns the Subordinates value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SubordinatesOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.Subordinates, nil
	}
	return nil, &NotLoadedError{edge: "subordinates"}
}

// BusinessOrErr returns the Business value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) BusinessOrErr() (*Business, error) {
	if e.Business != nil {
		return e.Business, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: business.Label}
	}
	return nil, &NotLoadedError{edge: "business"}
}

// StatusOrErr returns the Status value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) StatusOrErr() (*UserStatus, error) {
	if e.Status != nil {
		return e.Status, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: userstatus.Label}
	}
	return nil, &NotLoadedError{edge: "status"}
}

// AccessGroupsOrErr returns the AccessGroups value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AccessGroupsOrErr() ([]*UsersOnAccessGroups, error) {
	if e.loadedTypes[4] {
		return e.AccessGroups, nil
	}
	return nil, &NotLoadedError{edge: "access_groups"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldIsManager:
			values[i] = new(sql.NullBool)
		case user.FieldUserStatusID:
			values[i] = new(sql.NullInt64)
		case user.FieldName, user.FieldPassword, user.FieldPhotoURL, user.FieldDocument, user.FieldEmail:
			values[i] = new(sql.NullString)
		case user.FieldDeactivatedAt, user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case user.FieldID, user.FieldManagerID:
			values[i] = new(uuid.UUID)
		case user.ForeignKeys[0]: // business_users
			values[i] = new(sql.NullInt64)
		case user.ForeignKeys[1]: // user_business
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (u *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				u.ID = *value
			}
		case user.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				u.Name = value.String
			}
		case user.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				u.Password = value.String
			}
		case user.FieldIsManager:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_manager", values[i])
			} else if value.Valid {
				u.IsManager = value.Bool
			}
		case user.FieldPhotoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field photo_url", values[i])
			} else if value.Valid {
				u.PhotoURL = value.String
			}
		case user.FieldDocument:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field document", values[i])
			} else if value.Valid {
				u.Document = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				u.Email = value.String
			}
		case user.FieldManagerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field manager_id", values[i])
			} else if value != nil {
				u.ManagerID = *value
			}
		case user.FieldUserStatusID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_status_id", values[i])
			} else if value.Valid {
				u.UserStatusID = int(value.Int64)
			}
		case user.FieldDeactivatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deactivated_at", values[i])
			} else if value.Valid {
				u.DeactivatedAt = value.Time
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				u.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				u.UpdatedAt = value.Time
			}
		case user.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field business_users", value)
			} else if value.Valid {
				u.business_users = new(int)
				*u.business_users = int(value.Int64)
			}
		case user.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_business", value)
			} else if value.Valid {
				u.user_business = new(int)
				*u.user_business = int(value.Int64)
			}
		default:
			u.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (u *User) Value(name string) (ent.Value, error) {
	return u.selectValues.Get(name)
}

// QueryManager queries the "manager" edge of the User entity.
func (u *User) QueryManager() *UserQuery {
	return NewUserClient(u.config).QueryManager(u)
}

// QuerySubordinates queries the "subordinates" edge of the User entity.
func (u *User) QuerySubordinates() *UserQuery {
	return NewUserClient(u.config).QuerySubordinates(u)
}

// QueryBusiness queries the "business" edge of the User entity.
func (u *User) QueryBusiness() *BusinessQuery {
	return NewUserClient(u.config).QueryBusiness(u)
}

// QueryStatus queries the "status" edge of the User entity.
func (u *User) QueryStatus() *UserStatusQuery {
	return NewUserClient(u.config).QueryStatus(u)
}

// QueryAccessGroups queries the "access_groups" edge of the User entity.
func (u *User) QueryAccessGroups() *UsersOnAccessGroupsQuery {
	return NewUserClient(u.config).QueryAccessGroups(u)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *User) Update() *UserUpdateOne {
	return NewUserClient(u.config).UpdateOne(u)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (u *User) Unwrap() *User {
	_tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	u.config.driver = _tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", u.ID))
	builder.WriteString("name=")
	builder.WriteString(u.Name)
	builder.WriteString(", ")
	builder.WriteString("password=")
	builder.WriteString(u.Password)
	builder.WriteString(", ")
	builder.WriteString("is_manager=")
	builder.WriteString(fmt.Sprintf("%v", u.IsManager))
	builder.WriteString(", ")
	builder.WriteString("photo_url=")
	builder.WriteString(u.PhotoURL)
	builder.WriteString(", ")
	builder.WriteString("document=")
	builder.WriteString(u.Document)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(u.Email)
	builder.WriteString(", ")
	builder.WriteString("manager_id=")
	builder.WriteString(fmt.Sprintf("%v", u.ManagerID))
	builder.WriteString(", ")
	builder.WriteString("user_status_id=")
	builder.WriteString(fmt.Sprintf("%v", u.UserStatusID))
	builder.WriteString(", ")
	builder.WriteString("deactivated_at=")
	builder.WriteString(u.DeactivatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(u.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(u.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
