// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shared/infrastructure/persistence/postgres/ent/accessgroup"
	"shared/infrastructure/persistence/postgres/ent/user"
	"shared/infrastructure/persistence/postgres/ent/usersonaccessgroups"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UsersOnAccessGroupsCreate is the builder for creating a UsersOnAccessGroups entity.
type UsersOnAccessGroupsCreate struct {
	config
	mutation *UsersOnAccessGroupsMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (uoagc *UsersOnAccessGroupsCreate) SetUserID(u uuid.UUID) *UsersOnAccessGroupsCreate {
	uoagc.mutation.SetUserID(u)
	return uoagc
}

// SetAccessGroupID sets the "access_group_id" field.
func (uoagc *UsersOnAccessGroupsCreate) SetAccessGroupID(i int) *UsersOnAccessGroupsCreate {
	uoagc.mutation.SetAccessGroupID(i)
	return uoagc
}

// SetCreatedAt sets the "created_at" field.
func (uoagc *UsersOnAccessGroupsCreate) SetCreatedAt(t time.Time) *UsersOnAccessGroupsCreate {
	uoagc.mutation.SetCreatedAt(t)
	return uoagc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uoagc *UsersOnAccessGroupsCreate) SetNillableCreatedAt(t *time.Time) *UsersOnAccessGroupsCreate {
	if t != nil {
		uoagc.SetCreatedAt(*t)
	}
	return uoagc
}

// SetUpdatedAt sets the "updated_at" field.
func (uoagc *UsersOnAccessGroupsCreate) SetUpdatedAt(t time.Time) *UsersOnAccessGroupsCreate {
	uoagc.mutation.SetUpdatedAt(t)
	return uoagc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uoagc *UsersOnAccessGroupsCreate) SetNillableUpdatedAt(t *time.Time) *UsersOnAccessGroupsCreate {
	if t != nil {
		uoagc.SetUpdatedAt(*t)
	}
	return uoagc
}

// SetUser sets the "user" edge to the User entity.
func (uoagc *UsersOnAccessGroupsCreate) SetUser(u *User) *UsersOnAccessGroupsCreate {
	return uoagc.SetUserID(u.ID)
}

// SetAccessGroup sets the "access_group" edge to the AccessGroup entity.
func (uoagc *UsersOnAccessGroupsCreate) SetAccessGroup(a *AccessGroup) *UsersOnAccessGroupsCreate {
	return uoagc.SetAccessGroupID(a.ID)
}

// Mutation returns the UsersOnAccessGroupsMutation object of the builder.
func (uoagc *UsersOnAccessGroupsCreate) Mutation() *UsersOnAccessGroupsMutation {
	return uoagc.mutation
}

// Save creates the UsersOnAccessGroups in the database.
func (uoagc *UsersOnAccessGroupsCreate) Save(ctx context.Context) (*UsersOnAccessGroups, error) {
	uoagc.defaults()
	return withHooks(ctx, uoagc.sqlSave, uoagc.mutation, uoagc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uoagc *UsersOnAccessGroupsCreate) SaveX(ctx context.Context) *UsersOnAccessGroups {
	v, err := uoagc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uoagc *UsersOnAccessGroupsCreate) Exec(ctx context.Context) error {
	_, err := uoagc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uoagc *UsersOnAccessGroupsCreate) ExecX(ctx context.Context) {
	if err := uoagc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uoagc *UsersOnAccessGroupsCreate) defaults() {
	if _, ok := uoagc.mutation.CreatedAt(); !ok {
		v := usersonaccessgroups.DefaultCreatedAt()
		uoagc.mutation.SetCreatedAt(v)
	}
	if _, ok := uoagc.mutation.UpdatedAt(); !ok {
		v := usersonaccessgroups.DefaultUpdatedAt()
		uoagc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uoagc *UsersOnAccessGroupsCreate) check() error {
	if _, ok := uoagc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UsersOnAccessGroups.user_id"`)}
	}
	if _, ok := uoagc.mutation.AccessGroupID(); !ok {
		return &ValidationError{Name: "access_group_id", err: errors.New(`ent: missing required field "UsersOnAccessGroups.access_group_id"`)}
	}
	if _, ok := uoagc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsersOnAccessGroups.created_at"`)}
	}
	if _, ok := uoagc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UsersOnAccessGroups.updated_at"`)}
	}
	if _, ok := uoagc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UsersOnAccessGroups.user"`)}
	}
	if _, ok := uoagc.mutation.AccessGroupID(); !ok {
		return &ValidationError{Name: "access_group", err: errors.New(`ent: missing required edge "UsersOnAccessGroups.access_group"`)}
	}
	return nil
}

func (uoagc *UsersOnAccessGroupsCreate) sqlSave(ctx context.Context) (*UsersOnAccessGroups, error) {
	if err := uoagc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uoagc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uoagc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	uoagc.mutation.id = &_node.ID
	uoagc.mutation.done = true
	return _node, nil
}

func (uoagc *UsersOnAccessGroupsCreate) createSpec() (*UsersOnAccessGroups, *sqlgraph.CreateSpec) {
	var (
		_node = &UsersOnAccessGroups{config: uoagc.config}
		_spec = sqlgraph.NewCreateSpec(usersonaccessgroups.Table, sqlgraph.NewFieldSpec(usersonaccessgroups.FieldID, field.TypeInt))
	)
	if value, ok := uoagc.mutation.CreatedAt(); ok {
		_spec.SetField(usersonaccessgroups.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := uoagc.mutation.UpdatedAt(); ok {
		_spec.SetField(usersonaccessgroups.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := uoagc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersonaccessgroups.UserTable,
			Columns: []string{usersonaccessgroups.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uoagc.mutation.AccessGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersonaccessgroups.AccessGroupTable,
			Columns: []string{usersonaccessgroups.AccessGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accessgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccessGroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UsersOnAccessGroupsCreateBulk is the builder for creating many UsersOnAccessGroups entities in bulk.
type UsersOnAccessGroupsCreateBulk struct {
	config
	err      error
	builders []*UsersOnAccessGroupsCreate
}

// Save creates the UsersOnAccessGroups entities in the database.
func (uoagcb *UsersOnAccessGroupsCreateBulk) Save(ctx context.Context) ([]*UsersOnAccessGroups, error) {
	if uoagcb.err != nil {
		return nil, uoagcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uoagcb.builders))
	nodes := make([]*UsersOnAccessGroups, len(uoagcb.builders))
	mutators := make([]Mutator, len(uoagcb.builders))
	for i := range uoagcb.builders {
		func(i int, root context.Context) {
			builder := uoagcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsersOnAccessGroupsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uoagcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uoagcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uoagcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uoagcb *UsersOnAccessGroupsCreateBulk) SaveX(ctx context.Context) []*UsersOnAccessGroups {
	v, err := uoagcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uoagcb *UsersOnAccessGroupsCreateBulk) Exec(ctx context.Context) error {
	_, err := uoagcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uoagcb *UsersOnAccessGroupsCreateBulk) ExecX(ctx context.Context) {
	if err := uoagcb.Exec(ctx); err != nil {
		panic(err)
	}
}
